### ISSUE TITLE
Redirect awardsforall.org.uk to the under 10k page

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1005]
Redirect awardsforall.org.uk to the under 10k page.

**Comment by mattandrews** [comment]
This is tricky as I'm not sure whose responsibility this is. IT might be able to do it but they'll need to configure something at the HTTP level to do the redirect which they might not have resource to do. If we can get hold of a valid SSL cert for that domain we could do it ourselves via S3...?

**Comment by mattandrews** [comment]
Now done thanks to IT for sorting out SSL certs.

For future reference, if we want to do this again:

- Create an SSL cert in AWS Cert Manager (N. Virginia region) for the desired domain
- Ask IT to provision the required DNS records AWS asks for to verify this
- Create an S3 bucket for static website hosting, named after the domain
- Create a Cloudfront distribution pointed *at the S3 Website endpoint* (eg. `<bucket-name>.s3-website.eu-west-2.amazonaws.com`) and use the SSL cert from above
- Ask IT to create a CNAME for the domain pointing to the Cloudfront DNS name
- ????
- Profit
