### ISSUE TITLE
Design way of incorporating brand guidance to Logos page

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#101]
There is a brand guidance/how to use our logo document (to be sent to me shortly) that needs in some way to be incorporated into the Logos page. Users need to know the right way to use and present our logo.

We need to decide whether a straight pdf download is the best option, to incorporate the key info on the page itself, or do a combination of the two.

**Comment by stevekeene** [comment]
[BLF17_37 Acknowledgement-Logo-Guidance-04.pdf](https://github.com/biglotteryfund/blf-alpha/files/1124356/BLF17_37.Acknowledgement-Logo-Guidance-04.pdf)
[BLF17_37_website guidance_text-03 HW.docx](https://github.com/biglotteryfund/blf-alpha/files/1124357/BLF17_37_website.guidance_text-03.HW.docx)

Potential text for this page, and current logo guidance document, to inform design work...

**Comment by ChloeAlper** [comment]
Please see proposed solution attached (move across all three screens):
![logos-1](https://user-images.githubusercontent.com/27225981/27875925-f35da148-61ac-11e7-9277-df10c30d8429.png)
![logos-2](https://user-images.githubusercontent.com/27225981/27875945-0c783b02-61ad-11e7-87dc-d62200a28f08.png)
![logos-3](https://user-images.githubusercontent.com/27225981/27875970-18a1003a-61ad-11e7-83b6-e0403b588201.png)

**Comment by mattandrews** [comment]
This looks good, but my concern is that it might not solve Dave's concern about people not using the thing they're *obliged* to use (eg. they might not be specifically looking for the bilingual version as it may not occur to them they should be using it). 

Like, in these mockups, does the English one display by default, and you only see the bilingual one if you click that title? 

It might be a question of the copy: perhaps it should explicitly say something about projects running in Wales **needing** to use bilingual logos?

**Comment by stevekeene** [comment]
A few questions:

Does the "Success!" box/explanation of file format appear before or after someone has downloaded an image? It could be a really good feature, but feels like it would be most helpful before someone has downloaded, and would mean we could remove that copy from the text above.

Is there a way of incorporating more of the brand guidance document in the page itself? Looking at the download stats, I don't think enough people will actually download and read the pdf.

In terms of choosing English/bilingual logos/materials - is there a way of forcing people to answer that question first before they are allowed to proceed?

**Comment by ChloeAlper** [comment]
The idea was that the pop-up appeared after the user had downloaded their logo. I fear that putting a pop-up in between logo selection and clicking to download it may act as a barrier or nuisance. Please see attached storyboard for a different suggestion on how to deal with the issues at hand @stevekeene @mattandrews . I'm not sure how much of the guidance document to include in the fourth screen... We could technically replicate the whole document there:

![logo-download-storyboard](https://user-images.githubusercontent.com/27225981/27911263-5ad84352-6250-11e7-956b-adeacd2e3039.png)

**Comment by mattandrews** [comment]
This is neat – means there's less chance of people skimming it and just going straight to the (English) logos. Only way I think we could combine the two is have the logos still visible but greyed out/blurred or something underneath the buttons (to help clue people in that there's something there, once they select them) but really I think this page works (and we can track interactions to make sure people do click on it).

**Comment by stevekeene** [comment]
This looks really good, and great that we can then track interactions too. I think we need to finesse the wording a little, but the design principle and experience seems spot on.

**Comment by ChloeAlper** [comment]
Please see additional line of copy indicating why the user needs to pick a country, plus an attempt to improve the signposting throughout @stevekeene @mattandrews @TomSteinberg 
![blf-merch](https://user-images.githubusercontent.com/27225981/27963250-5656c9de-632c-11e7-92f3-7f95f893e282.png)

**Comment by ChloeAlper** [comment]
Note to self: following meeting decided to add more from guidance doc to fourth screen

**Comment by mattandrews** [comment]
This is mostly done but I haven't done the "download" box yet, eg. this:

![image](https://user-images.githubusercontent.com/394376/28322304-ac9fe0a6-6bcd-11e7-89a9-d10567f72a01.png)

This is because I don't have the text for this (besides the "use on websites" one) – can you provide this @ChloeAlper , so I can get it translated? Thanks!

**Comment by mattandrews** [comment]
(as in, the text for the other formats – print and vector)

**Comment by ChloeAlper** [comment]
Success! 

The logo you downloaded is ideal for use on websites.

If you need a bigger logo just close this box and select the Print or Vector versions.

——

Success! 

The logo you downloaded is ideal for print.

If you need a smaller logo for use online just close this box and select the Digital version, or, if you need an even bigger logo to give to a professional designer, select the Vector version.

——

Success! 

The logo you downloaded is ideal if you are working with a professional designer or working with large format print.

If you need a smaller logo just close this box and select the Print or Digital versions.

**Comment by mattandrews** [comment]
Thanks!

**Comment by mattandrews** [comment]
Now live on https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/grant-acknowledgement-and-logos/logodownloads/
