### ISSUE TITLE
Upload new versions of the 'small' logo to the Logos page

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#102]
Query from design team:
"On the website, the small versions of the logo are coming up really really small. Do you know why this is?"

New logos supplied:

![corporate_logo_rgb_pink_bilingual_small](https://user-images.githubusercontent.com/26818527/27627653-765cc98a-5be4-11e7-83e8-a1e470beeabb.jpg)
![corporate_logo_rgb_pink_small](https://user-images.githubusercontent.com/26818527/27627649-761d4bb6-5be4-11e7-9cbc-f3c4cb4a3a9b.jpg)
![corporate_logo_rgb_blue_bilingual_small](https://user-images.githubusercontent.com/26818527/27627648-76153192-5be4-11e7-8cc3-966174c02e64.jpg)
![corporate_logo_rgb_blue_small](https://user-images.githubusercontent.com/26818527/27627651-763814f0-5be4-11e7-993b-4ef2767fcf2d.jpg)

**Comment by mattandrews** [comment]
Fixed in https://github.com/biglotteryfund/blf-alpha/commit/6d29b5907b12e00fd2ca43ab6dbeb68714383cd4
