### ISSUE TITLE
Design and implement changes to the free merchandise page to reduce the chance that projects in Wales fail to use the correct, bilingual, Fund logo

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#103]

**Comment by ChloeAlper** [comment]
@stevekeene @mattandrews @TomSteinberg please see storyboard below as a proposed solution. The segmentation idea mimics that found on the storyboard at the end of #101 

![merch-order-storyboard](https://user-images.githubusercontent.com/27225981/27956209-a3a6fd9c-6310-11e7-944c-4701735719af.png)

Note: 'Thank you for your order...' message updated following customer feedback.

**Comment by ChloeAlper** [comment]
Please see additional line of copy indicating why the user needs to pick a country, plus an attempt to improve the signposting throughout
![blf-merch](https://user-images.githubusercontent.com/27225981/27963382-d1329a8e-632c-11e7-8f32-d2023c37e488.png)

**Comment by mattandrews** [comment]
Just to remind myself about the reason for doing this... when the user clicks Wales, should they only see the option to order the bilingual items? eg. they won't see the first option on this item:

![image](https://user-images.githubusercontent.com/394376/28277362-a86241c6-6b11-11e7-9e4d-1310bf22798b.png)

**Comment by mattandrews** [comment]
Now live on https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials
