### ISSUE TITLE
Create functionality for A/B testing allowing splitting traffic between old and new pages

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#106]
This relates to the https://github.com/biglotteryfund/blf-alpha/tree/proxy branch – we need a way to divide traffic between the old/new site for ramping up launches of new, large pages.

**Comment by TomSteinberg** [comment]
Before going ahead with this ticket find out how long a test would have to run before we learn anything.

**Comment by mattandrews** [comment]
I've made a [spreadsheet](https://docs.google.com/spreadsheets/d/1hpVSVrzj3F_vqhgQqqgBCvpHjI5OsJhApVpKbH_e63g/edit#gid=0) which attempts to calculate this.

It's tricky as there are [existing tools](https://docs.google.com/spreadsheets/d/1QaTLG9UNF7L25BXqCWBvXx3auTniDb9IvF6KmUOB2B8/edit?usp=drive_web) for calculating this stuff but we don't really have a conversion rate to measure here, do we?

My data takes an arbitrary number of users/visits to determine how long a test has to run for with a given cohort size. Right now I'm saying that 1000 people need to have seen something for us to be able to judge with confidence whether or not it was successful. Does that number sound right?
