### ISSUE TITLE
Improve explanation of ordering limit on plaques, within merch page

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#107]

**Comment by mattandrews** [comment]
Update after conversation on 10th November:

We should enforce one plaque per order.

**Comment by mattandrews** [comment]
@ChloeAlper / @yasheen this could do with some design input. What should this component look like when someone has ordered 1 plaque and can't add another one? How can we explain this?

![image](https://user-images.githubusercontent.com/394376/32722265-4830df44-c861-11e7-9f30-5eb249ccb304.png)

**Comment by mattandrews** [comment]
Now live [here](https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials).
