### ISSUE TITLE
Welsh speakers are unable to find the order form

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#109]
From Dave Symons:

>Another issue to raise – we’ve had a few calls from Welsh speakers trying to access the Welsh branded materials page (https://www.biglotteryfund.org.uk/welsh/funding/funding-guidance/managing-your-funding/ordering-free-materials)
> They are being directed to the equivalent old site page and, when they try to download the order form on that page, are finding it’s not available.
> It is only a few, so I’m not sure if it’s a caching issue on their setups, but it’s enough to have caught our attention so I thought I’d better raise it.

Need to work out what this is!

**Comment by mattandrews** [comment]
Ah – the problem is [this page](https://www.biglotteryfund.org.uk/wales/funding/funding-guidance/managing-your-funding/ordering-free-materials). It does have a link to the form, but if they "click here" they end up on the new form. But then, they don't need to download the order form – maybe we just need to make it clearer (temporarily?) that this page replaces the old order form?

**Comment by TomSteinberg** [comment]
Add the following to the merch page redirects:
https://www.biglotteryfund.org.uk/wales/funding/funding-guidance/managing-your-funding/ordering-free-materials
https://www.biglotteryfund.org.uk/scotland/funding/funding-guidance/managing-your-funding/ordering-free-materials
https://www.biglotteryfund.org.uk/england/funding/funding-guidance/managing-your-funding/ordering-free-materials
https://www.biglotteryfund.org.uk/northernireland/funding/funding-guidance/managing-your-funding/ordering-free-materials
