### ISSUE TITLE
Design, build and launch Page 2 - what to do soon after being awarded funding

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#11]
Design 'What you need to do soon after being awarded funding' page to point of sign-off, so that it is ready to handover to Matt.

**Comment by ChloeAlper** [comment]
![tblf-pdd 2-v1 2](https://cloud.githubusercontent.com/assets/27225981/24915983/af21d19e-1ed0-11e7-9953-4ea3fd0eda84.png)

**Comment by ChloeAlper** [comment]
Please see attachment @mattandrews @stevekeene @TomSteinberg :


![2-managing-your-funding-20170419](https://cloud.githubusercontent.com/assets/27225981/25173464/16b9c476-24ec-11e7-9394-6782e99d2e19.png)


I have adopted some of the existing illustrations because a) I think they work, b) we're more likely to  keep the creative team on side that way, and c) so that existing material such as this stays relevant...

![example](https://cloud.githubusercontent.com/assets/27225981/25173760/3fe4ae82-24ed-11e7-9065-c7758b51ce81.png) ...whether we end up replacing the PDF or not

**Comment by ChloeAlper** [comment]
@mattandrews look out for **2-managing-your-funding.psd**, copying over to our Dropbox now

**Comment by ChloeAlper** [comment]
Mobile version coming to you next FYI @mattandrews

**Comment by ChloeAlper** [comment]
@mattandrews isolated image should you need it: 
![img](https://cloud.githubusercontent.com/assets/27225981/25176690/f5d5f9a4-24f6-11e7-8aa5-60c5791ee42b.png)

**Comment by stevekeene** [comment]
Looks really good! 

A few comments:

- Is there any value in having some sort of call to action on the hero image? The "congratulations" works really nicely, but then you have to go a fair way down the page before you understand what you need to do.
- We're moving away from the use of stickman images - while it is part of the existing/legacy brand, it is unlikely to be part of the new one. 
- How will it be clear that those four boxes are clickable?
- Do you have the new Big Lottery Fund logo, as would be good to see that on the page? It likely to have been signed off by the time we go live with this page.

**Comment by ChloeAlper** [comment]
Thanks for your feedback @stevekeene 

• not sure I follow where the CTA would link to?
• That's a shame. Do you know what they are being replaced with/which illustrations or imagery are safe to use?
• I will add underlines to the headings and re-circulate to see if they feel more clickable amongst us 
• The logos I have been are all variants of this:
![screen shot 2017-04-19 at 13 01 56](https://cloud.githubusercontent.com/assets/27225981/25179204/c752dc14-2500-11e7-8cc1-87fa95657663.png)
...presumably they are wrong for this context?

**Comment by ChloeAlper** [comment]
@mattandrews @stevekeene @TomSteinberg mobile version attached:
![2-managing-your-funding-mobile-20170419](https://cloud.githubusercontent.com/assets/27225981/25179280/1e3b3fd0-2501-11e7-8e97-7803878e6646.png)

**Comment by stevekeene** [comment]
Hi @ChloeAlper 

The CTA comment was more food for thought than direction, and probably not that helpful! I guess I just thought it worth us considering if we could direct a little more, either just via copy (so amending the "Congratulations" text, or incorporating the links to other pages within the hero image (a decision I'll defer to you in terms of design and UX!).

Re: brand - I think this is just unfortunate timing in terms of where the brand is heading, which I appreciate leads to a difficult situation for you. It seems like the principle to follow currently is that the colours/fonts are OK, but best to use a light touch/not be led on anything else from the current guidelines. So we could either use photos, more generic imagery (eg social media icons for the social media box) or avoid further imagery altogether.

Sounds good on the clickable stuff - just want to make sure we cover off accessibility early.

For main logo - I believe we'll need the crossed fingers and pink circle to sit together.

Thanks for your patience on this! I think things will get easier in terms of brand over the next few weeks - I'm just trying to avoid a very good design getting derailed because of internal issues!

**Comment by ChloeAlper** [comment]
Mobile hero @mattandrews: 
![mob](https://cloud.githubusercontent.com/assets/27225981/25184806/64b41074-2513-11e7-9733-a6ade01ae720.png)

**Comment by ChloeAlper** [comment]
Logo updated and links made more obvious:
![2-managing-your-funding-20170419-2](https://cloud.githubusercontent.com/assets/27225981/25185738/0eb76fa6-2516-11e7-8b11-0de7ffbc4037.png)
As for moving the links into the hero I worry that this would affect the experience negatively by camouflaging them. I think it would be better to change the title copy if it's a concern

**Comment by ChloeAlper** [comment]
Updated mobile version:
![2-managing-your-funding-mobile-20170419-2](https://cloud.githubusercontent.com/assets/27225981/25186987/b4740190-2519-11e7-8fd8-822fcbb0689e.png)

**Comment by ChloeAlper** [comment]
2-managing-your-funding-mobile-20170419.psd copying across to the Dropbox @mattandrews

**Comment by ChloeAlper** [comment]
@stevekeene @TomSteinberg @mattandrews Page 2 with adjustments following Dawn's feedback:

![2-managing-your-funding-1-20170424](https://cloud.githubusercontent.com/assets/27225981/25332534/c3ae706e-28de-11e7-9f8b-d050202a5de9.png)

Second option:

![2-managing-your-funding-2-20170424](https://cloud.githubusercontent.com/assets/27225981/25332550/d053d516-28de-11e7-9be1-455794464643.png)

**Comment by stevekeene** [comment]
Looks excellent - thank you!

**Comment by mattandrews** [comment]
These look good – do we have a decision on which is final?

**Comment by ChloeAlper** [comment]
@stevekeene @TomSteinberg which version shall we go with? I prefer the first (more colours) but is the second safer?

**Comment by TomSteinberg** [comment]
@ChloeAlper I also prefer the first one, like Chloë says

**Comment by stevekeene** [comment]
Yep, me too. I think having four different colours helps differentiate each option.

**Comment by ChloeAlper** [comment]
Ok @mattandrews , I think that makes 2-managing-your-funding-1-20170424.png good to go

**Comment by ChloeAlper** [comment]
Mobile version attached @mattandrews @TomSteinberg @stevekeene 

![2-managing-your-funding-1-mobile-20170427](https://cloud.githubusercontent.com/assets/27225981/25485420/cbc66cb0-2b55-11e7-803c-9f6229046326.png)

Matt, things to note: the top bar is deeper, the logo is bigger, the font sizes have been increased, line-heights have been increased.

**Comment by stevekeene** [comment]
@ChloeAlper Looks excellent - happy to this to move to Matt!

**Comment by mattandrews** [comment]
Thanks!

I'm just making these changes, but struggling with the font sizes:

This is how it looks in the design:

![image](https://cloud.githubusercontent.com/assets/394376/25528507/1ce00e56-2c16-11e7-83f0-410ba7ae076b.png)

Whereas this is how it looks on the webpage, with the same font size (`32px`):

![image](https://cloud.githubusercontent.com/assets/394376/25528533/36a0cf06-2c16-11e7-8e47-f95ea60640d9.png)

I remember you saying @ChloeAlper that the PSDs are scaled up a bit (retina displays etc) – is `32px` right for this text or do we need to reduce it a bit?

**Comment by mattandrews** [comment]
Sorry, one other thing!

Not got a PSD for the desktop version of this, but it looks like the boxed-off text at the bottom ("Why are we asking you to do these things?") has a different background colour (and a border) between mobile/desktop – is this right? 

![image](https://cloud.githubusercontent.com/assets/394376/25531121/988ada90-2c20-11e7-81f9-3bedc6f7fc69.png)

Fine if so – I just need to add some conditional code to handle that, so let me know @ChloeAlper!

**Comment by ChloeAlper** [comment]
Hi @mattandrews , I stopped scaling up for retina because I could see it getting confusing. It looks like the web page rendering of Poppins is bolder than in PS so could we try knocking it down 1 or 2pt?

**Comment by ChloeAlper** [comment]
Ok I've corrected the backgrounds so that they're both the same; both boxes on both mobile and desktop are #fdfefe with a 50% opacity #cacaca 1px stroke:

![Uploading 2-managing-your-funding-mobile-20170502.png…]()
![Uploading 2-managing-your-funding-20170502.png…]()

Updated PSDs uploading to Dropbox

**Comment by TomSteinberg** [comment]
Header breaks between 'getting' and'National lottery' on iPhone 5C safari 602.1

**Comment by TomSteinberg** [comment]
Line break fixed.

Page built, translated, tested and launched. Now live at:

https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding

🛳
