### ISSUE TITLE
Design, build, test and launch 'Employees benefits' page, and link to from jobs page

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#110]
This page could be helpful for making sure job ads don't underplay our offer.

Raw text is at - https://biglotteryfund.org.uk/about-big/jobs/benefits

**Comment by mattandrews** [comment]
@ChloeAlper not urgent at all, but when we do this, would we just re-use the hero image from the main jobs page (eg. https://www.biglotteryfund.org.uk/jobs?

**Comment by mattandrews** [comment]
Also have added this as a way to navigate to the benefits page, let me know thoughts!

![image](https://user-images.githubusercontent.com/394376/29513010-d314b8b2-865b-11e7-905c-1fbd9fae7a0a.png)

**Comment by mattandrews** [comment]
... and when you're on the new benefits page, you can get back to the jobs page with this:

![image](https://user-images.githubusercontent.com/394376/29513027-e10c88b4-865b-11e7-9b8d-25db5be3d818.png)

(thoughts/feedback very welcome)

**Comment by mattandrews** [comment]
This is now live: https://www.biglotteryfund.org.uk/about-big/jobs/benefits
