### ISSUE TITLE
Change images on Ordering Free Materials page from blue to pink logo

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#111]
https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials

User feedback: "projects are getting confused receiving pink items when the photo shows blue items"

**Comment by mattandrews** [comment]
@stevekeene do we have images for this?

**Comment by stevekeene** [comment]
Images here: N:\Our Work\Teams\Digital, content & brand\Brand\Grant acknowledgement\Branding pics\pics for web

**Comment by mattandrews** [comment]
@stevekeene just to check, the only images I can see that show a pink item where they were blue before are the sticker sheets, eg:

## Before:

![image](https://user-images.githubusercontent.com/394376/29615096-8cfb7122-8804-11e7-8861-84d822c369f5.png)

## After:
![image](https://user-images.githubusercontent.com/394376/29615118-9b04cd22-8804-11e7-8446-1a8e9f0e9f5c.png)

... that sticker image (eg. pink stickers) is only in Welsh/bilingual, though – should the English one remain in blue?

Besides this, I've updated the images for some other items which look to have changed:

### Bilingual

- banner
- cheque
- plaque (aluminium)
- plaque (perspex)
- sticker sheet
- vehicle sticker

### Monolingual 
- banner
- cheque

... does this sound right? There were images in that set of some bunting but we don't currently offer bunting on the site?!

**Comment by stevekeene** [comment]
The team are going to send a new folder link with the right photos, and some minor copy edits for the items themselves (some of the sticker sheets aren't actually sticker sheets, but just one sticker).

And we will be offering bunting - but will raise that as a new item in due course!

**Comment by stevekeene** [comment]
Further update:

"All the pics have been sorted there will be no blue items from now. So can we replace the following photos please:

English   
Perpspex plaque
Small aluminium equipment plaque
Acknowledgment cheque
Vinyl banner                                                                                                              
Balloon 
A4 Sticker sheets
Small sticker 
Medium sticker
Large sticker

These are all saved as follows: N:\Our Work\Teams\Digital, content & brand\Brand\Grant acknowledgement\Branding pics\pics for web\English photos


Welsh  
Perspex plaque
Small alumiunium equipment plaque
Cheque
Vinyl banner
A4 sticker sheet
Small sticker
Medium sticker
Large sticker
Black vehicle sticker

These are all saved as follows: N:\Our Work\Teams\Digital, content & brand\Brand\Grant acknowledgement\Branding pics\pics for web\Welsh photos

The stainless steel plaques have changed and are on order so I won’t be able to get a pic of this until next week. I won’t include the bunting for now as it is likely we will change the website again further down the line."

And some copy changes to reflect new photos and to make clearer what people are actually ordering:

"•	Can we remove small sticker sheet please so that it reads small sticker and do the same please for medium and large as these should only read as medium sticker and large sticker, not sheet. 
•	Balloons – can we remove (pack of one) and replace with (individual)"

**Comment by stevekeene** [comment]
And the perspex plaques are back in stock!
