### ISSUE TITLE
Figure out a way to stop Craft including tracked changes formatting

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#1138]
We had some strikethroughs in text on the BBO programme page, presumably from copy/paste woes via Word. There's no easy way to remove this – maybe we could add a strikethrough toggle, or a clear formatting button?

**Comment by davidrapson** [comment]
https://imperavi.com/redactor/docs/settings/paste/#s-pasteinlinetags

Might be a workaround, if you remove `del` from that list? Worth a punt.

**Comment by mattandrews** [comment]
Looked into this – closing it for now due to complexity/confusion(!). The paste stuff doesn't seem to be the issue (I couldn't paste ~deleted text~ anyway), but trying to write a plugin was an exercise in pain when trying to deal with multiple selected elements (are they text nodes? are they inline? are they blocks? who knows?!). If we see more this coming up then let's re-open.
