### ISSUE TITLE
Add 'Did you find what you were looking for?' tool to the contact us page

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#115]

**Comment by mattandrews** [comment]
Just as a note-to-self, there's https://github.com/biglotteryfund/blf-alpha/tree/surveys which contains this work so far.

**Comment by mattandrews** [comment]
@ChloeAlper or @yasheen – for when we decide to pick this up, here's what we need:

The code I've got so far allows us to attach a "microsurvey" to a given URL (eg. `/about`, `/contact`). That survey consists of a question (eg. "Did you find what you were looking for?") and exactly two answers (eg. "Yes" and "No"). An answer can allow a "message", eg. if someone selects "No", a text box can appear giving them space to explain their choice. This is optional. All of the text is locale-specific (eg. will appear in Welsh on a Welsh page).

When someone takes a survey, a cookie is set so they won't see it again on that page. They can also click a cross icon to dismiss the survey and again, they won't see it.

At the moment there's no frontend to the survey results, but I envision building a simple webpage to show current surveys and their responses.

What we need is a design for this component: how should a microsurvey look? What do the different states look like (eg. if someone doesn't select an answer but tries to submit it, or if they submit an answer but the database is down and there was an error)? How does it work on mobile? Does the "message" field need a per-question title (eg. "Why did you say no?"), or can it be generic (eg. "Can you expand on your answer?").

One technical note that @TomSteinberg might have thoughts on: at the moment, to add a new survey (or close an existing one) requires a re-deploy of the app. This is probably acceptable right now but do we envision this being used frequently enough that the surveys should be "live" (eg. not hard-coded into the app)?

**Comment by ChloeAlper** [comment]
I know this isn't in the current sprint but it was sitting on my desktop almost finished, so I wanted to tie it up. Please see design attached @stevekeene @mattandrews @TomSteinberg 

Have a look at the bottom of the page where you'll find a new survey box and at the top of the page where you'll find the new hero/header. The content '1 of 6', 'how could we have made it better', etc is dummy pending discussion.

![4-contact-us-with-survey](https://user-images.githubusercontent.com/27225981/31773615-322417a0-b4db-11e7-8ae7-2af2b5b7a5e4.png)

and a suggested input box:
<img width="1398" alt="screen shot 2017-10-19 at 14 38 57" src="https://user-images.githubusercontent.com/27225981/31773650-4c784a90-b4db-11e7-814d-211b74937802.png">

**Comment by mattandrews** [comment]
I think this looks great – my only concern is that people might not make it all the way to the bottom of the page to see this.

Maybe underneath each section of this page there could be a call to action (like, a text/button link) that would then show the full form at the bottom?

**Comment by ChloeAlper** [comment]
@mattandrews please see design below.

Frame 1:
![4-contact-us-survey-frame-1](https://user-images.githubusercontent.com/27225981/32191184-1a463002-bda8-11e7-8b9b-80a8a5a36768.png)

Frame 2:
![4-contact-us-survey-frame-2](https://user-images.githubusercontent.com/27225981/32191248-4ed2b7fa-bda8-11e7-8801-eb83e0d308c3.png)

The idea is that the survey box would stick to the bottom edge of the browser. What do you think?

**Comment by ChloeAlper** [comment]
I meant to cc you on this too @davidrapson ☝️

**Comment by ChloeAlper** [comment]
I should have mentioned, the idea is that the survey box sticks to the bottom of the browser window:
![4-contact-us-survey-frame-1-browser](https://user-images.githubusercontent.com/27225981/32216757-bb33dba2-be1d-11e7-9e6f-0aa58b5b80ad.png)

**Comment by yasheen** [comment]
Thanks @ChloeAlper. @davidrapson, @stevekeene had some good insight from when we tested the homepage journey to above or below 10k pages. Many participants either didn't scroll at all, or they quickly scrolled up and down without reading anything. Perhaps we could help by showing the question after a certain amount of time instead of trying to guess where would be the best place to put it?

**Comment by mattandrews** [comment]
This is now live: https://www.biglotteryfund.org.uk/contact
