### ISSUE TITLE
Amendments/suggestions for the Jobs page - copy and visuals

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#117]
1. Revised copy for "Equalities" section:

_"The Big Lottery Fund is committed to advancing equalities, not only as a funder but also as an employer. This means we think about the needs and experiences of people from different backgrounds (for example, by gender, race, disability, religious belief and sexual orientation) and we work to ensure that there is equality of opportunity for all. It’s important to us that our staff reflect the diversity of the communities we serve. 
 
The Big Lottery Fund is proud to be a 'two tick' symbol user and is committed to interviewing applicants with a disability if they meet the minimum criteria for a job vacancy. We will make reasonable adjustments for disabled applicants at all stages of the selection process. To assist us, applicants should declare if they have a disability on the application form, and let us know of any requirements. 
 
If you have a disability that prevents you from completing an online form, please contact the HR Helpdesk, on 0121 345 8884 or email HRhelpdesk@biglotteryfund.org.uk, who will be happy to help.
 
The Big Lottery Fund has a disability forum open to disabled staff, and staff who have an interest in disability related issues for support, information sharing and advice. 
 
The Big Lottery Fund is proud to be a Stonewall Equality Champion, supporting our commitment to being a great place to work for lesbian, gay, bisexual and transgender (LGBT) staff. Working closely with Stonewall, we have established an LGBT staff network as a forum for championing support, knowledge sharing, influencing company policy and practice, and addressing LGBT issues at work."_

2. Bulletpoints under "What benefits are available?" to read:

_Generous Civil Service Pension scheme
Flexible working
Enhanced paid maternity/paternity/adoption leave
Paid volunteering leave 
Season ticket loan_

3. Add new staff quotes (to be supplied in the next couple of days) - these may replace the existing ones?

4. Look at how to visually represent our staff on the page

**Comment by mattandrews** [comment]
Have emailed for translation.

**Comment by mattandrews** [comment]
Have made these changes now – do we want to wait until we have new staff quotes or should this be a new ticket when they're done and translated?
