### ISSUE TITLE
Move assorted Tools to VPC/AD-auth app

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#1173]
There are three tools currently hosted within the main app which should be broken out:

1. Materials dashboard
2. Survey dashboard
3. Feedback dashboard

The challenge with all three is that they store content in a separate database (though in practice we could likely configure Sequelize in the new dashboard app to switch between different databases for different models), and the model definitions themselves would be needed in both apps. 

The latter problem is perhaps the biggest: how can we share these models? Git submodules? NPM packages? Possibly the dashboard app could become the single source of truth and could be an API for these things to submit data to, but this still feels clunky with form validation etc.

Thoughts welcome – the main thing we'd benefit from here is being able to remove the staff login concept from the existing dashboard (and eventually use that code solely for user-level accounts in future).

**Comment by mattandrews** [comment]
I guess because it adds a fair bit of extra importance/weight to that app, which is currently only concerned with funding application data. 

The clunk factor comes in the form of validation: we'd need to define all the expected fields for, say, the Materials order form, in both the Express webapp, but also at the API end to ensure it's valid. Or would we just assume if it had been allowed through the Express app then whatever data it's sending is okay? 

Thinking out loud too, I wonder if the existing Dashboard endpoint should have some sort of shared secret with the main app so that only it can `POST` to it (sort of like CSRF tokens)?

**Comment by davidrapson** [comment]
Closing in favour of https://github.com/biglotteryfund/blf-alpha/issues/1215
