### ISSUE TITLE
Design an alternative hero/header combination

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#119]
Explore a new look for the header and navigation following discussion with Jenny

**Comment by ChloeAlper** [comment]
Please see attachment @TomSteinberg 
I have left in the vox pop for now so that you can see the balance of the page but I can easily remove it 
![home-20170908](https://user-images.githubusercontent.com/27225981/30218718-b124258a-94b1-11e7-9178-a7f44c26eba7.png)

**Comment by ChloeAlper** [comment]
An alternative hero image @TomSteinberg :

![home-20170908-2](https://user-images.githubusercontent.com/27225981/30220408-3173987e-94b7-11e7-8cd0-f23394be0d93.png)

**Comment by ChloeAlper** [comment]
@TomSteinberg @stevekeene - treatment of hero images changed slightly to improve legibility:
![home-20170911-1](https://user-images.githubusercontent.com/27225981/30265357-d11c0cee-96d3-11e7-9a4f-2ff4bb486df6.png)

![home-20170911-2](https://user-images.githubusercontent.com/27225981/30265373-e3e9e698-96d3-11e7-8f47-e11163b7854a.png)

**Comment by ChloeAlper** [comment]
And now please see version 2 @TomSteinberg @stevekeene:

![home-20170911-1b](https://user-images.githubusercontent.com/27225981/30277532-ff08eaa6-96ff-11e7-8f1c-03460a073a19.png)

![home-20170911-2b](https://user-images.githubusercontent.com/27225981/30277541-03345156-9700-11e7-8314-8c4657bd9f82.png)

**Comment by ChloeAlper** [comment]
Updated PNGs attached for circulation @stevekeene , now with Twitter follow buttons.

[Home-page-20170911-2.zip](https://github.com/biglotteryfund/blf-alpha/files/1293184/Home-page-20170911-2.zip)

**Comment by ChloeAlper** [comment]
Version A1:
![home-version-a-1](https://user-images.githubusercontent.com/27225981/30284187-20b3f49a-9712-11e7-997d-3e0f64beb3b8.png)

Version A2:
![home-version-a-2](https://user-images.githubusercontent.com/27225981/30284200-2a696132-9712-11e7-929a-7c3c3b12b324.png)

Version B1:
![home-version-b-1](https://user-images.githubusercontent.com/27225981/30284207-326f11c4-9712-11e7-9ce9-996ebaa37089.png)

Version B2:
![home-version-b-2](https://user-images.githubusercontent.com/27225981/30284218-378cefbe-9712-11e7-99c1-e7389b71ad93.png)

**Comment by ChloeAlper** [comment]
Version A1 mobile:
![home-mobile-version-a-1](https://user-images.githubusercontent.com/27225981/30331475-d65e5cf0-97cf-11e7-8d51-3a5904f2f815.png)

Version B2 mobile:
![home-mobile-version-b-2](https://user-images.githubusercontent.com/27225981/30331493-e3143b40-97cf-11e7-9b37-268497f4b9c3.png)

**Comment by ChloeAlper** [comment]
Version B1 mobile:
![home-mobile-version-b-1](https://user-images.githubusercontent.com/27225981/30333652-511a9058-97d5-11e7-90d7-c4199e07559b.png)

**Comment by ChloeAlper** [comment]
And finally Version A2 mobile:
![home-mobile-version-a-2](https://user-images.githubusercontent.com/27225981/30334559-e0192a92-97d7-11e7-8c11-7add2a0403ec.png)

**Comment by ChloeAlper** [comment]
The 6 home page designs – 3 x desktop and 3 x mobile showing the three hero image rotations – are now ready and attached @TomSteinberg @stevekeene :

![home-desktop-20170921-1](https://user-images.githubusercontent.com/27225981/30694344-7b8ac31a-9ecb-11e7-9bf9-5ab8cd79e139.png)

![home-mobile-20170921-1](https://user-images.githubusercontent.com/27225981/30694378-9fbd4e88-9ecb-11e7-9c54-5319209910a9.png)

![home-desktop-20170921-2](https://user-images.githubusercontent.com/27225981/30694408-ca482006-9ecb-11e7-994e-014c9d0075f7.png)

![home-mobile-20170921-2](https://user-images.githubusercontent.com/27225981/30694412-ccba5a02-9ecb-11e7-9811-7e3a51aaeca9.png)

![home-desktop-20170921-3](https://user-images.githubusercontent.com/27225981/30694415-cefddfbe-9ecb-11e7-92f2-230638e73730.png)

![home-mobile-20170921-3](https://user-images.githubusercontent.com/27225981/30694419-d3127042-9ecb-11e7-94a4-0e1362f14f31.png)

**Comment by mattandrews** [comment]
This looks great! Nice work 👍 💯
