### ISSUE TITLE
Design, build test and launch Data page

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#12]
The MVP live version of this page should contain the following data:

- Total value of funding awarded
- Total number of grants awarded
- Number of grants under £10,000
- Total number of expected beneficiaries
- Value of funding awarded to trusts or with partners

It should *not* contain a search box in the first instance.

**Comment by ChloeAlper** [comment]
![data-20170413](https://cloud.githubusercontent.com/assets/27225981/25001451/7c5ca8ec-203d-11e7-95e9-d21486f6c37e.png)
Please see revisited data page attached @stevekeene @TomSteinberg @mattandrews

**Comment by ChloeAlper** [comment]
Sorry to put forward such change @mattandrews , it's just that I think the page is more balanced now and the information more digestible.

**Comment by ChloeAlper** [comment]
Showing rotations of the carousel: 
![data-our-year-in-numbers-rotation-2-20170413](https://cloud.githubusercontent.com/assets/27225981/25001670/75eba3c2-203e-11e7-9903-03363867cf1f.png)
![data-our-year-in-numbers-rotation-3](https://cloud.githubusercontent.com/assets/27225981/25001676/7d0b6aac-203e-11e7-9ea1-7cafc4717c3f.png)

**Comment by mattandrews** [comment]
Cool, this looks nice! Clean and simple. 👍

**Comment by TomSteinberg** [comment]
Great stuff. Some suggested improvements:
- Make sure that total amount of grant money, and the total number of grants are the first to things shown on the carousel
- It seems funny to have an e-bulletin link but not social media. I'd either remove it or add Facebook & Twitter alongside
- Drop the pennies from the total grant making, please

That's all!

**Comment by ChloeAlper** [comment]
@mattandrews @stevekeene @TomSteinberg please see attached. 
• Graphic treatment behind grant making changed and order changed
• E-bulletin link removed (will replace later with socials)
• Additional hero options supplied

![data-1-image-opt-1-20170413](https://cloud.githubusercontent.com/assets/27225981/25007414/62eb8dfe-2058-11e7-8279-98b0f27ac826.png)
![data-2-image-opt-1-20170413](https://cloud.githubusercontent.com/assets/27225981/25007420/66077f02-2058-11e7-9e3e-e6c62849e1c7.png)
![data-3-image-opt-1-20170413](https://cloud.githubusercontent.com/assets/27225981/25007429/695b5908-2058-11e7-8faf-df49809c1e4d.png)

Image option 2:
![data-1-image-opt-2-20170413](https://cloud.githubusercontent.com/assets/27225981/25007459/7a12cf2e-2058-11e7-81ac-a7f725b65350.png)

Image option 3 (though likely unable to use):
![data-1-image-opt-3-20170413](https://cloud.githubusercontent.com/assets/27225981/25007479/8e2ddbb6-2058-11e7-8bdc-d94b8a077f48.png)

**Comment by TomSteinberg** [comment]
The three drafts you've made using image option 1 are good to go in my view - nice work, you can pause on this for now.

**Comment by mattandrews** [comment]
I've got most of the way there with this, just need a PSD so I can grab those icons!

**Comment by ChloeAlper** [comment]
@stevekeene please see two options below:
![data-carousel-20170720](https://user-images.githubusercontent.com/27225981/28418587-211af682-6d54-11e7-837d-565fad54e9a7.png)
![data-20170720](https://user-images.githubusercontent.com/27225981/28418651-5b3e2f50-6d54-11e7-80af-f1c9c07ed36b.png)

**Comment by ChloeAlper** [comment]
Please see attachments @stevekeene 
• Page titles changed to reflect year relevant to data 
• Additional scrolling prompt added to carousel version 
• Icons tweaked

![data-carousel-20170721](https://user-images.githubusercontent.com/27225981/28466182-795d78ae-6e23-11e7-8fc5-f4a01b63f499.png)
![data-20170721](https://user-images.githubusercontent.com/27225981/28466258-c63ff732-6e23-11e7-95d3-89fcde553d30.png)

**Comment by stevekeene** [comment]
Small typo - number for centre square "Value of funding we paid out to our award partners" should be £10,805,105.

Thanks!

**Comment by ChloeAlper** [comment]
Typos corrected:
![data-20170724](https://user-images.githubusercontent.com/27225981/28513653-cca31942-704e-11e7-9eb9-703ed4aafe88.png)

**Comment by ChloeAlper** [comment]
Updated mobile and desktop versions attached:

 
![data-mobile-20170727](https://user-images.githubusercontent.com/27225981/28668691-fc2986fc-72c8-11e7-812d-9a528e754add.png)
![data-20170727](https://user-images.githubusercontent.com/27225981/28668692-fc2a52ee-72c8-11e7-93dc-1e411f5dcffb.png)

**Comment by ChloeAlper** [comment]
Annotated versions attached when you're ready @mattandrews :
![data-mobile-annotated](https://user-images.githubusercontent.com/27225981/28668794-76c166d2-72c9-11e7-8342-8448b689545d.png)
![data-annotated](https://user-images.githubusercontent.com/27225981/28668795-76c296ba-72c9-11e7-932f-edeaa0c49268.png)

**Comment by stevekeene** [comment]
Design signed off by Tom and Steve.

**Comment by mattandrews** [comment]
Closing as now live: https://www.biglotteryfund.org.uk/data 📈
