### ISSUE TITLE
Launch People's Projects programme page

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#1203]
- [x] Create draft programme page
- [x] Add approved hero image
- [x] Upload all guidance documents and provide URLs so they can be shared externally
- [x] Add welsh translation of page
- [x] Link to welsh version of video
- [x] Redirect legacy url (`/global-content/programmes/uk-wide/the-peoples-projects`)
- [x] Add vanity URL of `/thepeoplesprojects`

**Comment by davidrapson** [comment]
Oh hey this happened earlier this week 🚀 

https://www.biglotteryfund.org.uk/funding/programmes/the-peoples-projects
