### ISSUE TITLE
Welsh language press releases not available on legacy site

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#1209]
1. Visit https://www.biglotteryfund.org.uk/news-and-events and find a press release.
2. Find a Wales story, eg [this](https://www.biglotteryfund.org.uk/global-content/press-releases/wales/060818_wal_hwf_big-lottery-fund-helping-working-families-with-six-million-pound-fund)
3. Try to find the "Cymraeg" link, fail.
4. Turns out there [is a Welsh version](https://www.biglotteryfund.org.uk/welsh/global-content/press-releases/wales/060818_wal_hwf_big-lottery-fund-helping-working-families-with-six-million-pound-fund#) but no way to get to it.

This is because we don't proxy these pages and therefore don't inject the Cymraeg link. I think we did this originally because the search/pagination on the news page didn't work properly when proxied. Possibly we could proxy the articles themselves, though, and inject the Welsh link there?

Also worth noting: the news page honours a `region` cookie which used to be set by clicking these links:

![image](https://user-images.githubusercontent.com/394376/44261236-f34dbc80-a20e-11e8-8674-3f9f0dbff23f.png)

Unfortunately the new site doesn't update this when these links are clicked so if you had one set, your news landing page will always show region-specific news and you can never un-set it (until the cookie expires). Maybe we should start dropping/deleting those cookies?

**Comment by davidrapson** [comment]
We are close to replacing the whole news section so closing this one.
