### ISSUE TITLE
Update internal tools to use active directory authentication

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1215]
After discussing the pros-and-cons of the approach outlined in https://github.com/biglotteryfund/blf-alpha/issues/1173 we've determined that the simpler approach is to duplicate the active directory code from the applications service as the two dashboards have very different needs. 

The task is now to update internal tools to use active directory authentication.

- [x] Create a new active directory application for authenticating all-staff for internal tools (materials dashboard, feedback, survey etc.)
- [x] Separate out public login code/views from internal tools

**Comment by mattandrews** [comment]
Notes for future dev: some links on how to use multiple login strategies for Passport:

- https://stackoverflow.com/questions/20322384/how-to-serialize-deserialize-multiple-local-strategie
- https://github.com/passport/express-3.x-http-basic-and-digest-example

**Comment by mattandrews** [comment]
I have a branch (`staff-auth`) which successfully implements this. Needs a fair bit of tidying up but it's now possible to sign into the main app using Azure.

**Comment by mattandrews** [comment]
This is done 🎉
