### ISSUE TITLE
Copy change for Managing Your Funding page

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#122]
https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding

Change second para;

"We want you to be as flexible and creative as possible with using your grant money. However, you do need to publicly announce your funding award. Whilst we would love you to use a range of ways to do this, here are some you should consider:"

to 

"We ask that you publicly announce your funding award. Whilst we would love you to use a range of ways to do this, here are some you should consider:"

**Comment by mattandrews** [comment]
It might be good when we make these tickets in future to get the translation in Welsh upfront and have it listed in this ticket, then we can just pick it up and do it! Will wait for Dave to finish all his work and pick this up next week.
