### ISSUE TITLE
Migrate our people section

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1280]
- [x] Board
- [x] Senior management team
- [x] England committee
- [x] Northern Ireland committee
- [x] Wales committee
- [x] Scotland committee
- [x] UK funding committee
- [x] Once all other pages are live, archive /about-big/our-people/directors-expenses as documents are now inline

**Comment by mattandrews** [comment]
A quick look suggests that [this](https://github.com/biglotteryfund/blf-alpha/blob/master/modules/legacy.js#L54) addition (eg. the `<base>` tag) fixes those images – worth extending that to all envs for a quick fix?

Agree that migrating the pages is a good shout, though.

**Comment by davidrapson** [comment]
Pages are with the relevant subject matter experts for review. Leaving this in blocked until some feedback comes back in.

**Comment by davidrapson** [comment]
superseded by wider about section ticket https://github.com/biglotteryfund/blf-alpha/issues/1561

**Comment by davidrapson** [comment]
Re-opening this one. Keeping the larger pages as standalone tickets.

**Comment by davidrapson** [comment]
Board and UKFC pages have been send for some welsh translation amends and then can be launched.

**Comment by davidrapson** [comment]
UKFC page is now live at https://www.biglotteryfund.org.uk/about/our-people/uk-funding-committee

Board page is pending a check of new photos, and then ready to go.
