### ISSUE TITLE
Design structure of initial EYP application process 

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#129]
The programme homepage and associated tabs

**Comment by ChloeAlper** [comment]
Please see EYP landing page wire attached @stevekeene @mattandrews @TomSteinberg 
![ewp-tips-20170801](https://user-images.githubusercontent.com/27225981/28819714-fee40a20-76a6-11e7-8180-4a4aecde5724.png)

**Comment by ChloeAlper** [comment]
I'm still tweaking it but here's a little preview of the first tab: 
![eyp-tab1](https://user-images.githubusercontent.com/27225981/29275380-d801639c-8102-11e7-831c-6f0869d6b25a.png)

**Comment by mattandrews** [comment]
This is really nice 👍 

How would the four tabs work on mobile? Right now we kinda get away with it as we only have 2 tabs at a time:

![image](https://user-images.githubusercontent.com/394376/29322339-16c5c2c6-81d5-11e7-8893-28e0f40ab4b3.png)

**Comment by ChloeAlper** [comment]
I was thinking of using an accordion for mobile, what do you think?

**Comment by mattandrews** [comment]
Yeah, could work!

**Comment by ChloeAlper** [comment]
Cool. 
Tab 1/landing screen styling updated slightly:
![eyp_tab1_20170815](https://user-images.githubusercontent.com/27225981/29322664-2eaf3d8a-81d6-11e7-92ae-bb334dafa115.png)

**Comment by ChloeAlper** [comment]
@TomSteinberg please see four EYP tabs below:

1
![eyp-tab1-20170815](https://user-images.githubusercontent.com/27225981/29334502-801541d2-81ff-11e7-879b-8ade1fee9fc2.png)

2
![eyp-tab2-20170815](https://user-images.githubusercontent.com/27225981/29334589-d1748416-81ff-11e7-97e4-a49760ffc126.png)

3
![eyp-tab3-20170815](https://user-images.githubusercontent.com/27225981/29334652-0ebbb592-8200-11e7-9e79-0afcd91ad8e2.png)

4
![eyp-tab4-20170815](https://user-images.githubusercontent.com/27225981/29334871-c792a9fe-8200-11e7-8b44-68c3b1d08463.png)
