### ISSUE TITLE
Launch beta version of past grants to a percentage of visitors

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1317]
Requirement to decide on approach for _how_ we want to roll this out and what percentage.

**Comment by mattandrews** [comment]
## Non-team tasks
- [ ] Get new data
- [ ] add Welsh translation (do we need area names too?)
- [ ] Re-add time facet (depends on above)

## Team tasks
- [ ] Add organisation type facet/filter
- [ ] Build organisation page
- [ ] Build landing page
- [ ] Add funding programme autocomplete
- [ ] Add country name to raw data
- [ ] Add a way to link case studies with grant IDs
- [ ] Add analytics (including hotjar search text)
- [ ] Run a load test

**Comment by mattandrews** [comment]
We probably need to add a "Last updated on..." date somewhere, too.

**Comment by davidrapson** [comment]
Now live 🎉
