### ISSUE TITLE
Redirect stray logos page URL

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#133]
Redirect https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/grant-acknowledgement-and-logos/LogoDownloads to https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/grant-acknowledgement-and-logos/logodownloads

Old page currently showing up top of Google results for 'biglotteryfund logos', sigh

ALSO there are /wales /scotland variants for this, all still live, because of course...

**Comment by mattandrews** [comment]
Bizarrely we already have https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/grant-acknowledgement-and-logos/logodownloads which works – note the `logodownloads` vs `LogoDownloads`! Will add the extra one.

**Comment by mattandrews** [comment]
Now live!
