### ISSUE TITLE
EYP - Get sign off for wireframes showing structure

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#135]
Subticket of #134

**Comment by ChloeAlper** [comment]
Four wireframes are in the zip attached, alternatively you can see them in this clickable prototype: https://invis.io/CBCX3B96V
Please let me know whether you are happy for these to go to Amanda @TomSteinberg @stevekeene 
[EYP-wires.zip](https://github.com/biglotteryfund/blf-alpha/files/1204383/EYP-wires.zip)

**Comment by ChloeAlper** [comment]
Please see updated prototype @TomSteinberg : https://invis.io/T9CX5C1EF

**Comment by ChloeAlper** [comment]
Updated wire prototype: https://invis.io/T9CX5C1EF
