### ISSUE TITLE
EYP - Creative signed off

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#136]
This is a sub ticket of #134

**Comment by ChloeAlper** [comment]
@stevekeene please see attached 'brief' for the designer to run past HW. It needs to be no wider than 955px please, height doesn't really matter. I can run through the brief with them if we get the green light. I will need to drop it into my creative on Wednesday morning ready for testing on Thurs. 
![how-to-diagram-sketch](https://user-images.githubusercontent.com/27225981/29127296-95894dec-7d18-11e7-9473-0346be4614b5.png)

**Comment by ChloeAlper** [comment]
@stevekeene , for the 'how to' illustration:

• Please provide an editable creative file (PSD, AI, ID)
• Width no wider than 955px
• Height ideally under 300px
Asset pack (fonts, PSD): https://www.dropbox.com/sh/9zka13thh04ih5i/AACLCTdmnoiTTOGlSXJrBg9ca?dl=0
