### ISSUE TITLE
Allow media aside in flexible content pages to link to assets with file picker

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1396]
To avoid needing to link to files directly like this

![image](https://user-images.githubusercontent.com/123386/47419469-2f078400-d774-11e8-982a-7936c1fc807e.png)

Should support both plain link (for urls) and file picker (for assets)

**Comment by mattandrews** [comment]
Could also do this with the vanity aliases, some of which point to files.
