### ISSUE TITLE
Description text spilling out of bounding box on Ordering Free Materials page

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#142]
Some merch item description copy exceeds the width of bounding box when page is at medium width:

![screen shot 2017-08-08 at 11 26 08](https://user-images.githubusercontent.com/27225981/29068882-702c0294-7c30-11e7-8730-12321b265cc5.png)

**Comment by mattandrews** [comment]
Good spot – just pushed a fix out to improve this:
![image](https://user-images.githubusercontent.com/394376/29069370-a79f489c-7c32-11e7-9af5-4b1a82c807fd.png)
