### ISSUE TITLE
Post-launch grants search tweaks

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1430]
- [x] If coming to an existing search where the option is hidden expand facets by default
- [x] If cancelling a search mid-query the promise should also be cancelled
- [x] Trim search query before searching
- [x] Add timeout to requests and log any over the threshold
- [x] Disable other controls when search is loading (eg. sort)
- [x] Refactor recipient API call, reduce work needed to fetch recipient page details
- [x] Bug: when on "no results" screen, clearing the query and pressing enter has no effect
- [x] Add tracking for spellchecker usage
- [x] Show the search filter summary on the error screen (eg. for removal of individual filters)
- [ ] The "awarding programme" list should link to the funding programme page, not a search
- [ ] Tidy up spellchecking (eg. on numbers)
- [ ] Improve loading behaviour when scrolled down the page
- [ ] Improve experience of filter selection causing pages to drop to the bottom when loading
- [ ] Add an "Active grant" filter option
- [ ] Improve facets for `amountAwarded` (eg. inclusive/exclusive buckets)
- [ ] Add a dynamic location lookup button
- [ ] Allow advanced search with multiple parameters (eg. programmes)
- [ ] Add a datepicker for custom date ranges

**Comment by mattandrews** [comment]
- [ ] Improve facets for `amountAwarded` (eg. inclusive/exclusive buckets)

**Comment by mattandrews** [comment]
###  The "awarding programme" list should link to the funding programme page, not a search

This one is tricky as the `fundingProgramme` facet which we use to display this list doesn't get augmented with a URL.

**Comment by mattandrews** [comment]
https://www.tnlcommunityfund.org.uk/funding/grants?awardDate=2018-01-01%7C2018-12-31&sort=amountAwarded%7Cdesc

![image](https://user-images.githubusercontent.com/394376/55472887-1e9de400-5605-11e9-9307-efcd5ea8691c.png)

The `awardDate|asc` shouldn't be showing here when reloading the page.
