### ISSUE TITLE
Rebuild /About page of the website

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#145]
This includes: 
- [x] Produce initial sketches / wireframes of possible design approach to this section #146 
- [x] ~~Do early user testing based on wireframes or prototypes~~
- [x] Design and get sign-off for main /About page
- [x] Build new /About page
- [x] Test and launch new /About page
- [ ] Design, build test an launch new sub-pages to /About page

**Comment by yasheen** [comment]
![about-20170904-mobile](https://user-images.githubusercontent.com/4420387/30032618-e9cb09e2-918e-11e7-843e-229be801e8b3.png)

![about-20170904](https://user-images.githubusercontent.com/4420387/30032626-f5bae894-918e-11e7-8e28-dc2aa993600f.png)

**Comment by yasheen** [comment]
![about-20170926-mobile](https://user-images.githubusercontent.com/4420387/31078186-0c487798-a779-11e7-9f73-d2a807ff4eb9.png)

This time, we're going mobile first. We'll also present a design rationale to help content writers: 
[2017-09-27_WhoIsTheAboutPageFor.pdf](https://github.com/biglotteryfund/blf-alpha/files/1348943/2017-09-27_WhoIsTheAboutPageFor.pdf)

**Comment by davidrapson** [comment]
This has now happened.
