### ISSUE TITLE
Sketch / wireframe page that shows all grant programmes available in NI for grants over £10k

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#147]
There seem to be just two such programmes: https://www.biglotteryfund.org.uk/funding/funding-finder?area=Northern+Ireland&amp;amount=50001%20-%20500000

**Comment by yasheen** [comment]
![147_0results](https://user-images.githubusercontent.com/4420387/31880530-bcdb5930-b7d8-11e7-96c1-9900d02a03fe.jpg)
![147_2results](https://user-images.githubusercontent.com/4420387/31880531-bcf120c6-b7d8-11e7-8386-a3a9a33903be.jpg)
![147_16results](https://user-images.githubusercontent.com/4420387/31880532-bd066882-b7d8-11e7-9f45-a55734005125.jpg)

**Comment by davidrapson** [comment]
Closing as this is covered by https://www.biglotteryfund.org.uk/funding/programmes?location=northernIreland&min=10000
