### ISSUE TITLE
Design, Build and Launch Page 1 - the logos page

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#15]
This page helps people to understand how to use the Fund's logo on their site or publicity

**Comment by ChloeAlper** [comment]
@stevekeene @mattandrews @TomSteinberg please see creative: 

![1-how-to-tell-people-about-your lottery-funding-using-our logo-20170425](https://cloud.githubusercontent.com/assets/27225981/25396619/12a598ce-29dd-11e7-9c7f-6f8d738665e3.png)

**Comment by stevekeene** [comment]
Hi @ChloeAlper  - looks good!

I think we should probably just double check we have the right logos - I can speak to the brand team about this, if that is helpful.

**Comment by ChloeAlper** [comment]
Please find mobile version attached @stevekeene , @TomSteinberg , @mattandrews 

![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-20170427](https://cloud.githubusercontent.com/assets/27225981/25495191/38499d4e-2b74-11e7-8a03-b78bc0cba7ab.png)

**Comment by ChloeAlper** [comment]
Updated mobile version attached. Note: 
• button width reduced 
•space between buttons increased 
•new logos switched in (aside from the black version as it was not supplied/has perhaps been discontinued) 
•line height increased 
•characters per line reduced

![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-20170502](https://cloud.githubusercontent.com/assets/27225981/25621511/79ecd648-2f49-11e7-8ffd-6fb3d69abf92.png)

**Comment by stevekeene** [comment]
OK - logo update!

Logos will be OK, but haven't got the official nod yet. That should happen in the next week or so.

I will check on that black and white logo that is missing "National". It either needs to read "National Lottery Funded" like the others, or be removed.

**Comment by ChloeAlper** [comment]
New logos (in body) and new logo (header) hmmm. Please have a look @stevekeene 
![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-20170503](https://cloud.githubusercontent.com/assets/27225981/25653036/0645e370-2fe3-11e7-999c-548dcc484b45.png)

**Comment by ChloeAlper** [comment]
@stevekeene , further to our conversation I've added the full logo(s) to a mobile screen to give people a contextual view. The cropped version is my preference, justifiable because of the space restrictions I hope:

![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-full-logo](https://cloud.githubusercontent.com/assets/27225981/25656970/64de3cf6-2ff3-11e7-9a6c-b5456828fd53.png)

![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-full-welsh-logo](https://cloud.githubusercontent.com/assets/27225981/25656974/6bc68c62-2ff3-11e7-9285-970cc494a840.png)

![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-cropped-logo](https://cloud.githubusercontent.com/assets/27225981/25656993/88eea464-2ff3-11e7-9b9a-2b7888567116.png)

**Comment by mattandrews** [comment]
Does the new logo have to be in that layout, or can the "National Lottery Funded" text sit alongside the BLF logo rather than below it?

**Comment by ChloeAlper** [comment]
The people generating the logo would need to do that. I'd rather keep the mobile version a bit cleaner if we can...

**Comment by stevekeene** [comment]
Thanks @ChloeAlper - leave this one with me.

**Comment by ChloeAlper** [comment]
Updated with correct logos:
![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-20170503-2](https://cloud.githubusercontent.com/assets/27225981/25668905/eaed0b8e-301f-11e7-8115-08aa360d7319.png)

**Comment by ChloeAlper** [comment]
Mobile version updated with correct logos:
![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-](https://cloud.githubusercontent.com/assets/27225981/25669648/04f078f2-3022-11e7-9fae-389ba15733dc.png)

**Comment by ChloeAlper** [comment]
@stevekeene @TomSteinberg @mattandrews how about this for a new design warning: 

![different-design-explanation-20170510](https://cloud.githubusercontent.com/assets/27225981/25899192/d5f4d2c2-3586-11e7-953b-7aae9a4e91b7.png)

**Comment by mattandrews** [comment]
Works for me. Maybe we could have slightly friendlier text? Is there anyone who can write a line for us, @stevekeene?

**Comment by TomSteinberg** [comment]
Rendering bug - on iPhone with safari 602.1 the header breaks across two lines

**Comment by TomSteinberg** [comment]
Built, tested, launched. Now live at https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/grant-acknowledgement-and-logos/logodownloads
