### ISSUE TITLE
Design EYP product home

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#151]
Produce research report
Amend design
Amend copy
Get signoff
Create handover doc
Mob version
Run through checklist

**Comment by ChloeAlper** [comment]
Please see creative ready for sign-off @mattandrews  @TomSteinberg @stevekeene 

Desktop:
![eyp-tab1](https://user-images.githubusercontent.com/27225981/29675267-9aed9394-88ec-11e7-8c1a-bd606427a820.png)

![eyp-tab2](https://user-images.githubusercontent.com/27225981/29675277-9fbd3d66-88ec-11e7-881f-f58e380bdd78.png)

![eyp-tab3](https://user-images.githubusercontent.com/27225981/29675289-a6d8a3c4-88ec-11e7-8958-5e0d44abd2f3.png)

![eyp-tab4](https://user-images.githubusercontent.com/27225981/29675295-ab834f64-88ec-11e7-951a-bfd9455d5454.png)

![eyp-tab4b](https://user-images.githubusercontent.com/27225981/29675304-afebd4cc-88ec-11e7-8d76-9c2fc4add76b.png)

Mobile:

![eyp-mobile-tab1](https://user-images.githubusercontent.com/27225981/29675329-c342dd2c-88ec-11e7-99a8-0b16844ced6d.png)

![eyp-mobile-tab4](https://user-images.githubusercontent.com/27225981/29675331-c5aadd80-88ec-11e7-8c39-cbee52bae540.png)

**Comment by ChloeAlper** [comment]
Updated mobile designs attached @mattandrews . Changes made:
• Buttons made taller
• Spacing increased 
• Subtle stroke added to case study content boxes

![eyp-tab1](https://user-images.githubusercontent.com/27225981/29825309-f1375eaa-8ccb-11e7-8f22-a93c25a787fc.png)
![eyp-tab4](https://user-images.githubusercontent.com/27225981/29825316-f4ee3582-8ccb-11e7-902b-7e0701c26855.png)

**Comment by ChloeAlper** [comment]
Handover doc:
![eyp-mobile](https://user-images.githubusercontent.com/27225981/29826784-22db73ca-8cd0-11e7-9655-4882910c4fa8.png)
