### ISSUE TITLE
Update copy on the merch page to make it more obvious that merchandise is free

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#153]
Usability testing revealed that several users failed to realise that BLF merchandise is free. Copy/titles need to signal this better

**Comment by mattandrews** [comment]
Think this is done now since the recent updates – mentions "free" multiple times:

![image](https://user-images.githubusercontent.com/394376/36418977-8a502460-1628-11e8-8e2b-e5517eaaa00d.png)
