### ISSUE TITLE
Migrate about section pages based on audit

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#1561]
Migrate or archive the following pages

## Funding programmes

- ~Create funding programme page for https://www.biglotteryfund.org.uk/about-big/iwill~ Extracted to https://github.com/biglotteryfund/blf-alpha/issues/1630

## General pages

- [x] Add welsh language standards to footer quick links
- [x] Archive https://www.biglotteryfund.org.uk/about-big/big-lottery-fund-in-your-constituency 
- [x] Archive https://www.biglotteryfund.org.uk/about-big/future-of-doing-good
- [x] Archive https://www.biglotteryfund.org.uk/about-big/mayors-community-weekend
- [x] Archive https://www.biglotteryfund.org.uk/about-big/your-voice
- [x] Archive https://www.biglotteryfund.org.uk/about-big/countries
- [x] Archive https://www.biglotteryfund.org.uk/about-big/living-wage
- [x] Migrate https://www.biglotteryfund.org.uk/about-big/thankstoyou-toolkit
- [x] Migrate https://www.biglotteryfund.org.uk/about-big/publications/corporate-documents
- [x] Archive https://www.biglotteryfund.org.uk/about-big/publications
- ~Migrate Dormant accounts (https://www.biglotteryfund.org.uk/about-big/dormant-account-statement-of-intent, https://www.biglotteryfund.org.uk/about-big/dormant-account-statement-of-intent) to funding section. This may need looking at post 30 Jan, as we could end up with a very long funding section as it stands. (Note: Combine into two pages if possible?)~ Extracted to https://github.com/biglotteryfund/blf-alpha/issues/1631

## Our approach

- [x] Redirect https://www.biglotteryfund.org.uk/about-big/our-approach to /about
- [x] Redirect https://www.biglotteryfund.org.uk/about-big/our-approach/about-big-lottery-fund to /about
- [x] Archive https://www.biglotteryfund.org.uk/about-big/our-approach/vision-and-principles
- [x] Migrate https://www.biglotteryfund.org.uk/about-big/our-approach/international-funding to funding section
- [x] Migrate https://www.biglotteryfund.org.uk/about-big/our-approach/non-lotttery-funding to funding section
- [x] Redirect https://www.biglotteryfund.org.uk/about-big/our-approach/accessibility to current accessibility policy
- [x] Migrate https://www.biglotteryfund.org.uk/about-big/our-approach/equalities to about section, link to from quick links in footer

## Our People

- ~Migrate all remaining people pages and redirect our people section to /about/our-people~ Extracted to https://github.com/biglotteryfund/blf-alpha/issues/1280

**Comment by davidrapson** [comment]
Closing this as I've extracted any remaining more complex pages into separate tickets (people, iwill, dormant accounts).
