### ISSUE TITLE
Redirect all old programme urls to new programmes archive

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1597]
All archived and legacy programme pages have been imported in at least a basic form under https://www.biglotteryfund.org.uk/funding/programmes/all

Investigate implementing a wild-card redirect (or some more granular solution) for each programme from the old /global-content/programmes/* url to the equivalent /funding/programme/* url

**Comment by mattandrews** [comment]
Now live! https://www.biglotteryfund.org.uk/global-content/programmes/england/changing-spaces etc.
