### ISSUE TITLE
Build replacement sitemap page

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1609]
We have a robot version of this page at https://www.biglotteryfund.org.uk/sitemap.xml so some of the code for this exists. The task is to build a replacement for https://www.biglotteryfund.org.uk/sitemap

**Comment by mattandrews** [comment]
Possibly relates to https://github.com/biglotteryfund/blf-alpha/issues/1476 too, eg. thinking about how we might automatically list known URLs between both the webapp and the CMS.
