### ISSUE TITLE
Fix line lengths on all new pages/in style guide

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#164]
CF https://baymard.com/blog/line-length-readability
- [ ] Specify em line-length (on Roboto and then Poppins)
- [ ] Apply to content boxes, titles (anything else?)

**Comment by mattandrews** [comment]
Yep – @ChloeAlper has something about this in the styleguide that we should look at.

From that blogpost:

>In order to avoid the drawbacks of too long and too short lines, but still energize your readers and keep them engaged, we suggest keeping your text within the range of 50-75 characters per line.

A very unscientific measure of an [arbitrary page](https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding) on our largest breakpoint (eg. it won't get bigger than this as the width becomes fixed) has 19 words on a line – 97 characters.

**Comment by mattandrews** [comment]
Just looking into this. Setting a `max-width` of 33em on `<p>` elements gives this result when viewed on my 15" Macbook:

![image](https://user-images.githubusercontent.com/394376/32884451-4ac08c0c-cab2-11e7-983b-9e6cca52247e.png)

@yasheen + @ChloeAlper, are you happy with this?

**Comment by mattandrews** [comment]
Closing due to lack of movement.
