### ISSUE TITLE
Upgrade CMS to Craft 3.1

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1645]
https://craftcms.com/blog/craft-3-1

- [x] Upgrade to Craft 3.0.39 — Required before upgrading to 3.1.x
- [x] Create a new elastic beanstalk environment to test craft upgrade, deploy from a separate branch
- [x] Create a new database (cloned from production)
- [x] Upgrade to latest Craft 3.1.x version
- [x] Test effect of `'allowAdminChanges' => false,`, especially on user permission updates
- [x] Set `useProjectConfigFile` to `false`
- [x] Run SuperTable migration steps
- [x] Configure all credentials sorted in new Project Config to come from secrets or environment variables.
- [x] Set `useProjectConfigFile` to `true`
- [x] Test workflow for updating project config from development environment through to a live environment
- [x] Set `allowAdminChanges` to false in non-development environments. Ensures project config is read only outside of development
- [x] Update `preview-button` to support environment variable for URL?
- [x] Once happy with upgrade and project config workflow, sync database, cut over to the new environment.

**Comment by mattandrews** [comment]
Created a new branch `upgrade`, which deploys to `craft-production-green`.

Next step is to do the upgrade there!

**Comment by mattandrews** [comment]
Have just merged https://github.com/biglotteryfund/craft-dev/pull/146 into `upgrade`.

**Comment by mattandrews** [comment]
I think I've done the SuperTable stuff (eg. visited `/actions/super-table/plugin/check-content-tables` and `/actions/super-table/plugin/fix-content-tables`)... will have to do this again when re-exporting the DB, though.

**Comment by mattandrews** [comment]
Done!
