### ISSUE TITLE
Add analytics of some sort to the CMS

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#1683]

**Comment by mattandrews** [comment]
Started looking at this and realised it's not obvious how to add arbitrary code to the CMS templates. Clearly it's possible (the admin panel CSS plugin does it) but equally wasn't trivial either.

**Comment by davidrapson** [comment]
Could you use https://github.com/doublesecretagency/craft-cpjs ?

**Comment by mattandrews** [comment]
Done!
