### ISSUE TITLE
Remove leftover old-style hero images

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1715]
- [x] Confirm that no old style images are used on the site, replace any that need replacing
- [x] Remove supporting code from main app which references old images
- [x] Remove references to old field from the API
- [x] Duplicate the `heroNew` field on the API as `hero`
- [x] Remove duplicate hero field names from the API
- [x] Remove references to old trail and thumbnail images from main app
- [x] Remove all references to old trail and thumbnail images from API
- [x] Duplicate any new `*New` trail image fields under their amended names in the API
- [x] Replace any remaining references to old trail images from the main app
- [x] Remove duplicate trail image field names from the API
- [x] Replace all references to `heroNew` with `hero` in the main app
- [x] Remove old hero fields from all entry types in the CMS
- [x] Delete old hero fields from the CMS

**Comment by davidrapson** [comment]
No unblocked as #1645 is done

**Comment by mattandrews** [comment]
Now done!
