### ISSUE TITLE
Linking to Welsh entries from Craft renders links to English pages

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1786]

**Comment by mattandrews** [comment]
It looks like this is deliberate behaviour in Craft: https://github.com/craftcms/cms/issues/2956 we will have to wait for a fix.

**Comment by mattandrews** [comment]
(see also: https://github.com/craftcms/cms/issues/2006)

**Comment by mattandrews** [comment]
Waiting on this to get released: https://github.com/craftcms/redactor/pull/187

**Comment by mattandrews** [comment]
Done now we've updated the CMS!
