### ISSUE TITLE
Prevent style attributes on embedded videos from controlling width

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#1789]
eg. this code: `<iframe style="width:500px;height:281px;" src="//player.vimeo.com/video/315446070" frameborder="0"></iframe>` can cause this result:

![image](https://user-images.githubusercontent.com/394376/53729143-5bdb4e80-3e6c-11e9-9553-c0fdf604e818.png)

We should be able to remove/ignore these attributes on embedded stuff.

**Comment by davidrapson** [comment]
I think we can set these options in the htmlpurifier config, possibly http://htmlpurifier.org/live/configdoc/plain.html#HTML.AllowedAttributes
