### ISSUE TITLE
Design, build & launch page 3 - how to get branded merch

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#18]

**Comment by TomSteinberg** [comment]
I had some thoughts on how an MVP version of this might work that wouldn't involve building a multi-page flow. Here goes.

1 - Each kind of item you can order has a + and - button under/next to it, along with a running total (that starts at zero)

2 - The first time you press '+' on anything, a page element appears with a link that says 'Order now'

3 - Following the order now link simply sends you down to the bottom of the same page, to where an order form sits directly under the last item that can be ordered. This form copies all the current fields from the downloadable version, and has a 'submit' button at the end.

**Comment by stevekeene** [comment]
Supplier's needs - to be sent via email:

- Item(s) ordered
- Code(s) of items ordered
- Quantity of each item
- Contact name
- Address to send items
- Phone number
- Email address

We also ask for:

- Project name
- Project ID
- Amount of grant

I suspect this is to put off people without funding ordering stuff, but I think we can challenge this in the spirit of MVP, or at least restrict it to project ID.

Our brand team need:

- To set maximum order
- Remove items
- Add items
- See orders (nice to have, not critical)

I would say only setting a maximum order is essential for the first iteration.

**Comment by mattandrews** [comment]
Thanks – they'll need the amount project name / grant amount for the big cheque, I guess? I can configure it so they only get asked for that info if they select that item, though.

**Comment by stevekeene** [comment]
I'll check on that - not sure if we just send through a blank cheque, so to speak.

**Comment by ChloeAlper** [comment]
Here is a formless version of the page:

![3-how-to-get-free-branded-materials](https://cloud.githubusercontent.com/assets/27225981/25811347/e3d5d170-340a-11e7-8922-53dc38362de7.png)

A version with ordering functionality will follow.

**Comment by ChloeAlper** [comment]
![page-3-form-sketch](https://cloud.githubusercontent.com/assets/27225981/25893182/c5bbf718-356e-11e7-983e-540240974c99.jpg)

**Comment by ChloeAlper** [comment]
Please see design attached @TomSteinberg @stevekeene @mattandrews 

![3-how-to-get-free-branded-materials](https://cloud.githubusercontent.com/assets/27225981/26050900/6504ba16-3958-11e7-978f-1f67eab2e519.png)

**Comment by TomSteinberg** [comment]
Very interesting @ChloeAlper 

Please could you show us a tiny excerpt showing what it would looke like if someone opened up one of the selectors, especially if there are several options?

**Comment by stevekeene** [comment]
Looks good! I like the uniform nature of the boxes, will give us flexibility to add and remove when these products change in the future without ruining the design.

Will there be any sort of message or prompt once "Add" has been clicked, to show user they need to scroll down to complete the order? Or should we assume that is standard behaviour for now and test once it is live?

And will there be a "Thank you for your order"-type message once the order has been placed, and will that sit on this page or a new one?

**Comment by ChloeAlper** [comment]
@TomSteinberg @stevekeene @mattandrews please see landing screen, 'product selected' screen and 'thank you for your order' pop-over screen attached: 

![3-how-to-get-free-branded-materials-landing-screen](https://cloud.githubusercontent.com/assets/27225981/26149473/5065a764-3af2-11e7-9c0e-114b6f800cde.png)

![Uploading 3-how-to-get-free-branded-materials-product-selected.png…]()

![Uploading 3-how-to-get-free-branded-materials-pop-over.png…]()

**Comment by ChloeAlper** [comment]
Item selected:
![3-how-to-get-free-branded-materials-product-selected](https://cloud.githubusercontent.com/assets/27225981/26149977/6b4a5eba-3af4-11e7-9fab-1748c20b08a5.png)

**Comment by ChloeAlper** [comment]
![3-how-to-get-free-branded-materials-pop-over](https://cloud.githubusercontent.com/assets/27225981/26150050/a8abd5cc-3af4-11e7-81d2-4abcbe6b77b1.png)

**Comment by ChloeAlper** [comment]
Showing error/validation message in form section:
![3-how-to-get-free-branded-materials-validation-message](https://cloud.githubusercontent.com/assets/27225981/26150359/f9def3d8-3af5-11e7-9d81-83b07962bc98.png)

**Comment by TomSteinberg** [comment]
Looking really strong!

Just one request, which is that when a product is added (i.e any number selected that's more than zero) it would be great if there could be more visual signalling than the very subtle change of number and change of colour in the minus button. Maybe you could put the whole product name, controls and number onto a little highlighted rectangle, or similar?

My goal here is that someone who has ordered three things from different parts of the page can easy see that they have selected three things, as their eye scans across the page.

**Comment by TomSteinberg** [comment]
@ChloeAlper Required change: every time the word 'Welsh' appears under a photo it should be replaced with 'Welsh & English'

**Comment by ChloeAlper** [comment]
@stevekeene @TomSteinberg @mattandrews , please see changes attached:
![3-how-to-get-free-branded-materials-20170517-2](https://cloud.githubusercontent.com/assets/27225981/26159056/7450111e-3b15-11e7-8fe9-0df136fc16fc.png)

**Comment by stevekeene** [comment]
@ChloeAlper I really like that - super clear.

**Comment by stevekeene** [comment]
You can type in the numbers boxes - you can also type letters in there! Maybe best that you can't type in there at all?

**Comment by TomSteinberg** [comment]
Excellent stuff! 👍 

 Things to fix: 
- When I click on a plus button it draws a blue rectangle round the button, which is some kind of artifact that shouldn't be there.
- When a product has a long title e.g  'Stainless steel plaque (310mm x 260mm)' it pushes the image further down the page than when it has a short title.

**Comment by stevekeene** [comment]
There is prompt when address line 2 isn't filled in. People may not have a second address line, so perhaps this shouldn't be mandatory?

**Comment by mattandrews** [comment]
Thanks all.

@TomSteinberg – that rectangle is a browser default. We can [remove it](http://www.outlinenone.com/) and rely on the background colour change to make it clear it's active etc?

The title thing is tricky with a responsive site – we don't know the width of the item boxes in advance (it's all proportional to the screen size). The only fix for this would be to make the site "adaptive" rather than responsive: see [here](https://css-tricks.com/the-difference-between-responsive-and-adaptive-design/) for details on that.

@stevekeene yes, good point. Would be good to get a list of which fields we consider mandatory for this? At the moment I've made them all required, not sure what we need though.

**Comment by TomSteinberg** [comment]
OK - on the blue rectangle that's a browser default, please remove that since the current experience is like pressing a key on a keyboard and finding that it's stuck down.

On the title thing, no need to make that size of change now, this is a nice to have that I'll ticket separately if it still bugs me. But it's clearly not a UX deal breaker.

On the address details, I would make everything mandatory except for county and address line 2

**Comment by ChloeAlper** [comment]
Here's the annotated doc we talked about @mattandrews 
![3-how-to-get-free-branded-materials-handover](https://cloud.githubusercontent.com/assets/27225981/26193527/7cb6ba22-3bad-11e7-935b-925ebe03c387.png)

**Comment by ChloeAlper** [comment]
And the pop-over: 
![3-how-to-get-free-branded-materials-pop-over-handover](https://cloud.githubusercontent.com/assets/27225981/26193791/2e9883b0-3bae-11e7-9a39-c1b34dd41617.png)

**Comment by mattandrews** [comment]
Question on this: what should happen if someone fills out the form (their details) without having chosen any products?

**Comment by ChloeAlper** [comment]
The 'place order' button would be greyed out, but do you think we need an instruction too?

**Comment by mattandrews** [comment]
No, that's probably fine. Thanks!

**Comment by ChloeAlper** [comment]
Asterisk added to mark mandatory fields:
![3-how-to-get-free-branded-materials copy](https://cloud.githubusercontent.com/assets/27225981/26315138/11bbe8e2-3f08-11e7-88bd-9904f5e7b6f9.png)

**Comment by mattandrews** [comment]
Closing this as it's now live.
