### ISSUE TITLE
Improve performance of funding programmes listing API.

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1814]
We're requesting more information that we need for listing pages.

**Comment by mattandrews** [comment]
Spent a bit of time on this today. Managed to reduce size / improve speed by:

- hard-coding the `/funding` page to only request 3 (not 100) programmes, ordered by last modified date
- removing most of the "content" fields from the `/funding-programmes/` endpoint where a slug isn't provided

... but the biggest improvement by far was by switching on GZIP for nginx locally:

## Before
![Screenshot 2019-03-20 15 33 34](https://user-images.githubusercontent.com/394376/54697659-d9b67f80-4b25-11e9-827e-44084b0892b3.png)
## After
![Screenshot 2019-03-20 15 33 40](https://user-images.githubusercontent.com/394376/54697661-d9b67f80-4b25-11e9-9a72-387e7350d785.png)

... so we should probably work out how to do that for Apache on EB.

**Comment by mattandrews** [comment]
Update: [this guide](http://www.tonmoygoswami.com/2013/05/how-to-enable-gzip-on-amazon-elastic.html) is basically spot-on, except it needs `application/json` adding to the mime types. Just tried it on test but unfortunately it doesn't do much to the overall load time, but it does reduce the data sent over the wire once it's complete.

**Comment by davidrapson** [comment]
Nice work, I think the other thing to explore will be to remove any "related" calls that aren't needed for listing pages (e.g. checking for related project stories), anything where we have to make cross-entry lookups for things.

**Comment by mattandrews** [comment]
Yeah, have done that too (basically I've chopped out anything that isn't needed to render the listing).

**Comment by mattandrews** [comment]
See https://github.com/biglotteryfund/blf-alpha/pull/1834 and https://github.com/biglotteryfund/craft-dev/pull/166

**Comment by mattandrews** [comment]
These changes are now live and things are a bit speedier.
