### ISSUE TITLE
Submit search removal requests for old documents

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#1818]
Submit removal requests to https://www.google.com/webmasters/tools/removals for any old documents that are still indexed by google.

Relates to #1811

Look at analytics for views under `/-/media/Files` for candidates to remove. They should start to go away on their own now that the document archive page reports a 404 but if we can speed things up then all the better.

**Comment by mattandrews** [comment]
Had a go at this. Looks like [it's not possible](https://webmasters.stackexchange.com/questions/33411/how-to-remove-thousands-of-urls-from-google-cache) to do it in bulk, and we have about [1700+](https://www.google.co.uk/search?ei=NCOnXJ-IHvWV1fAPwZuluA8&q=site%3Abiglotteryfund.org.uk%2F-%2Fmedia&oq=site%3Abiglotteryfund.org.uk%2F-%2Fmedia&gs_l=psy-ab.3...17770.17770..18195...0.0..0.46.46.1......0....2j1..gws-wiz.pZ8uSpsp29E) of them on the legacy site (just 3 on the new one, so the 404 error is working).
![image](https://user-images.githubusercontent.com/394376/55619152-0dcda980-5790-11e9-998e-8606fd781cd4.png)

Think we'll just have to wait this out, unless we want to manually submit each one.
