### ISSUE TITLE
Design, build & launch page 18 - How to get press coverage

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#19]

**Comment by ChloeAlper** [comment]
@stevekeene @mattandrews @TomSteinberg please see design attached:

![18-how to get press coverage for your grant](https://cloud.githubusercontent.com/assets/27225981/26214283/b6fdce14-3bf3-11e7-8cac-21dba70c4073.png)

**Comment by ChloeAlper** [comment]
Mobile version attached:
![18-how to get press coverage for your grant-mobile](https://cloud.githubusercontent.com/assets/27225981/26312562/e9a864e6-3eff-11e7-9a04-117b18368356.png)

**Comment by ChloeAlper** [comment]
@mattandrews please find desktop handover doc attached 
![18-how to get press coverage for your grant-handover](https://cloud.githubusercontent.com/assets/27225981/26316871/94bc4f0c-3f0d-11e7-891a-dcd51bcd0a8c.png)
![18-how to get press coverage for your grant-mobile-handover](https://cloud.githubusercontent.com/assets/27225981/26317249/c815376e-3f0e-11e7-81cb-4ab8a85b6226.png)

**Comment by ChloeAlper** [comment]
@stevekeene @TomSteinberg please check you are happy with the updated generic images:
![18-how to get press coverage for your grant-mobile](https://cloud.githubusercontent.com/assets/27225981/26447256/9bf0ef88-413f-11e7-8d21-b811420fb1ea.png)

**Comment by ChloeAlper** [comment]
@stevekeene @mattandrews @TomSteinberg please see desktop page design without generic images: 
![18-how to get press coverage for your grant-20170525](https://cloud.githubusercontent.com/assets/27225981/26452465/01202730-4158-11e7-9dae-a2324a76362d.png)

**Comment by mattandrews** [comment]
Looks fine to me, if a little lonely :(

**Comment by stevekeene** [comment]
I think this looks great - very clear and easy to digest the info.

**Comment by ChloeAlper** [comment]
And here is a version with images from our bank. Please have a look @stevekeene @mattandrews :
![18-how to get press coverage for your grant-20170525-2](https://cloud.githubusercontent.com/assets/27225981/26452987/fdcf5de2-4159-11e7-8a1c-6be83428ac48.png)

**Comment by ChloeAlper** [comment]
Note: the email address in the last 'tell us about your success' section is incorrect (it had a note against it in the PDD)

**Comment by stevekeene** [comment]
I think these images work much better than the stock images, even though I appreciate they aren't quite so relevant.

Do you have a preference between these two new versions @ChloeAlper?

**Comment by ChloeAlper** [comment]
I think the version with images breaks up the information more and therefore makes it a bit easier to digest. Let me know the final call @stevekeene and I will apply to same treatment to the contact page

**Comment by stevekeene** [comment]
@ChloeAlper OK, let's go with the second version with our images rather than stock images - thanks Chloe!

**Comment by mattandrews** [comment]
Great! @ChloeAlper when you get a chance can you send me the images used (and the two hero images for desktop/mobile)? Just waiting on these.

**Comment by ChloeAlper** [comment]
Sure @mattandrews , preparing the PSD now

**Comment by ChloeAlper** [comment]
@mattandrews **18-how to get press coverage for your grant.psd** is now in our Dropbox

**Comment by mattandrews** [comment]
Thanks! There's actually an item missing on the newer designs (the "Draft a press release" one), so for the last item ("Tell us about your success stories") I reused the first photo and the first colour (blue). If this is wrong, let me know what image to use etc!

**Comment by ChloeAlper** [comment]
Missing section added: (cc @mattandrews )
![18-how to get press coverage for your grant copy 2](https://cloud.githubusercontent.com/assets/27225981/26636249/08885a86-4614-11e7-9490-e93a75b1ae9e.png)

**Comment by mattandrews** [comment]
😎
