### ISSUE TITLE
Deliver three more case studies (and improve the authoring process at the same time)

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#198]

**Comment by ChloeAlper** [comment]
New vox pop ready to be added to the home page carousel @davidrapson @mattandrews 
<img width="1001" alt="screen shot 2017-10-09 at 11 44 17" src="https://user-images.githubusercontent.com/27225981/31337334-ba1c3e12-acf2-11e7-860e-3cdf0bbd8ead.png">

**Text:**

"My motivation in wanting to do youth work comes from knowing the impact that Bytes had and continues to have on me." 

Anthony Turkington
Beneficiary
Bytes

**Image Crops:**

/Dropbox (Big Lottery Fund)/Big Lottery Fund Team Folder/Digital Creative/Page 28 - Home/Assets/vox-pop-3-mob.jpg and vox-pop-3-desktop.jpg

**Comment by davidrapson** [comment]
@ChloeAlper Thanks Chloe, I'll get this added now.

**Comment by ChloeAlper** [comment]
New vox pop ready to added to the carousel @davidrapson @mattandrews :
<img width="1020" alt="screen shot 2017-10-09 at 10 45 44" src="https://user-images.githubusercontent.com/27225981/31443144-8214922c-ae90-11e7-92ec-9e0a42f617ea.png">

**Case Study Link:**
https://www.biglotteryfund.org.uk/funding/big-stories/passion4fusion

**Text:**
"I am helping make sure that young people get the opportunities they want in terms of education."
 
Jonathan Ssentamu
Youth Development Worker
Passion4Fusion

**Image Crops**
Dropbox (Big Lottery Fund)/Big Lottery Fund Team Folder/Digital Creative/Page 28 - Home/Assets/vox-pop-4-mob.jpg and vox-pop-4-desktop.jpg

**Comment by ChloeAlper** [comment]
Parking this here as a reminder to myself to launch this vox pop when we are displaying more case studies that will dilute current seemingly sporty focus:

<img width="1017" alt="screen shot 2017-10-10 at 10 21 56" src="https://user-images.githubusercontent.com/27225981/31443843-689e13a2-ae92-11e7-8142-ca60be0489b0.png">

Unable to generate 5th vox pop for HP until we're supplied another case study
