### ISSUE TITLE
Ensure that all users clicking on country links on the above 10k page are served pages that meet their expectations

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#201]

**Comment by mattandrews** [comment]
This is now live – visitors to the [Over £10k](https://www.biglotteryfund.org.uk/over10k) page will now see a filtered (proxied) Funding Finder, eg: https://www.biglotteryfund.org.uk/funding/funding-finder?area=Wales&over=10k
