### ISSUE TITLE
Update all new style pages to reflect new nav/header/hero images

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#202]
Replaces #87 

- [x] Update existing hero images to use new aspect-ratio images: small, medium, large imagery
- [x] Document hero components in styleguide (super-hero & section-hero)

**Comment by ChloeAlper** [comment]
Hero (all pages but HP) cropping template: Dropbox (Big Lottery Fund)/Big Lottery Fund Team Folder/Digital Creative/Assets/Templates/hero-cropping-templates.psd
