### ISSUE TITLE
Fix layout issues caused by over running text on press release pages

### ISSUE THREAD

**Issue by LynseyJReynolds** [biglotteryfund/blf-alpha#2082]
e.g. 
<img width="1387" alt="Screen Shot 2019-07-18 at 15 13 47" src="https://user-images.githubusercontent.com/14089243/61467271-3d857380-a973-11e9-9320-62f35c090cb2.png">
<img width="1251" alt="Screen Shot 2019-07-18 at 15 13 35" src="https://user-images.githubusercontent.com/14089243/61467272-3d857380-a973-11e9-9e8c-a194a4cbfebb.png">

**Comment by mattandrews** [comment]
Closing this as the [page in question](https://www.tnlcommunityfund.org.uk/news/press-releases/2019-07-18/100million-national-lottery-climate-action-fund-launched-for-communities-across-the-uk) has fixed it by making the long URL a clickable text phrase instead, which is the easiest fix here.
