### ISSUE TITLE
Phone number validation not working

### ISSUE THREAD

**Issue by NikhilNanjappa** [biglotteryfund/blf-alpha#2183]
### What
For the main/senior contact's phone number field, if we enter the value "4444", it passes validation.

Another scenario when the long number (of say 85 characters) long is added, the form on submission hangs.

### Solutions Implemented
Already tried adding the `.max` validation to the field but the behavior persisted.

### Expected
Should fail validation on all the above occasions.

**Comment by davidrapson** [comment]
By the looks of this issue, `joi-phone-number` is a bit lax https://github.com/Salesflare/joi-phone-number/issues/57

We could either fork it and make the fix suggested there and/or in the short-term write our own version of this validator with the required changes.

**Comment by NikhilNanjappa** [comment]
True. it doesn't seem like their library itself is throwing an error for it - https://npm.runkit.com/joi-phone-number.

We could also use the `google-libphonenumber` directly.

**Comment by davidrapson** [comment]
Yeah, I reckon so, or write our own version of that validator. We have plenty of other custom validators and the actual code is straightforward.  Just tried updating our `node_modules` source directly to include a call to `PhoneUtil.isValidNumber(number)` and it does the job, so reckon that's the way to go
