### ISSUE TITLE
Investigate capturing screenshots of site on each build?

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#243]
Automate capture of screenshots for designs in progress

**Comment by TomSteinberg** [comment]
It's a very interesting idea. In order for them to be useful it would probably have to capture at 3 different screen widths though, I suspect.

**Comment by davidrapson** [comment]
I have something like that in progress at https://github.com/biglotteryfund/blf-alpha/pull/248 which aims to capture a small / medium / large screenshot of key pages.

**Comment by davidrapson** [comment]
Covered as part of https://github.com/biglotteryfund/blf-alpha/pull/248
