### ISSUE TITLE
Make changes to the jobs page in order to support the new England recruiting

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#274]

**Comment by ChloeAlper** [comment]
Please see design attached @TomSteinberg @stevekeene 
• Jobs table added (I didn't transcribe the full list but hopefully this is enough to give you the gist) 
• extra logo added
![jobs-20171018](https://user-images.githubusercontent.com/27225981/31726681-7e9748d0-b41f-11e7-93f4-debbced470ae.png)

**Comment by ChloeAlper** [comment]
Have improved the shading in the hero, reduced size of logo and added the hero caption:

![jobs](https://user-images.githubusercontent.com/27225981/31761646-8f749e0a-b4b0-11e7-87b3-3e009e229ae6.png)

**Comment by davidrapson** [comment]
Jobs listing added as part of https://github.com/biglotteryfund/blf-alpha/pull/287, waiting on list of links before this goes out to the test site.

**Comment by davidrapson** [comment]
Jobs page is now live so closing this one.
