### ISSUE TITLE
Replace funding finder results with new page(s) for users on 10k+ journey

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#275]
Involves:
- Further CMS work
- Design
- Testing
- Building

**Comment by ChloeAlper** [comment]
Please see below @mattandrews @yasheen @davidrapson @stevekeene @TomSteinberg - a suggestion for the Funding Finder Results page following yesterday's meeting 

![funding-finder-results-20171024](https://user-images.githubusercontent.com/27225981/31949172-9807d946-b8d0-11e7-95d6-6cb80e3c1f3c.png)

**Comment by mattandrews** [comment]
Looks good! Would equal height boxes be easier to scan?

**Comment by davidrapson** [comment]
Aesthetically I really like this, there's definitely something to this in terms of how you are handling information density.

Couple of minor observations:

- I think there are less than 20 active funding programmes at the moment, so we can most likely get away without pagination list everything.
- This might just be me but circular photos feel a little over-stylish at the expense of clarity
- My only concern about the staggered layout is the political-factor of what order things are in (but I do really like the look of it)

👍

**Comment by ChloeAlper** [comment]
Thanks for the feedback @davidrapson and @mattandrews . I'll mock up another version with your comments in mind.

**Comment by ChloeAlper** [comment]
@davidrapson @mattandrews please see design below. Changes made:
• Boxes made equal height
• Photos made square 
• Pagination removed 

![funding-finder-results-20171030](https://user-images.githubusercontent.com/27225981/32167415-b25056cc-bd60-11e7-8a0e-7e3d7fe25016.png)

**Comment by davidrapson** [comment]
👍

**Comment by TomSteinberg** [comment]
For a quick upgrade without having deeply reconsidered the content, this is good and almost ready to go. The only thing that I think is essential to change is that you can't have a the middle > wales > as a link because there's no actual page to link to there. The breadcrumb trail can only have to parts, or if you want three, add the homepage.

**Comment by stevekeene** [comment]
Looks good to me!

**Comment by davidrapson** [comment]
> For a quick upgrade without having deeply reconsidered the content, this is good and almost ready to go. The only thing that I think is essential to change is that you can't have a the middle > wales > as a link because there's no actual page to link to there. The breadcrumb trail can only have to parts, or if you want three, add the homepage.

In this example you have actually filtered by wales which does exist as a page in this context (https://test.blf.digital/funding/programmes?location=wales), so this should probably read "Funding programmes over 10k > Programmes in Wales (16)" or similar. But agree there should only be two items.

**Comment by ChloeAlper** [comment]
Update below:
<img width="680" alt="screen shot 2017-10-30 at 12 38 40" src="https://user-images.githubusercontent.com/27225981/32171227-5be5784e-bd6f-11e7-950a-7f6daec13dd8.png">

**Comment by davidrapson** [comment]
These pages are now live 🎉  https://www.biglotteryfund.org.uk/funding/programmes?min=10000&location=england
