### ISSUE TITLE
Redesign and relaunch 'Helping Working Families Fund' product page

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#276]

**Comment by ChloeAlper** [comment]
Landing page sketch: 
![hwf-landing-sketch](https://user-images.githubusercontent.com/27225981/32220113-6957905c-be28-11e7-89c9-af339447f4cf.jpg)

**Comment by ChloeAlper** [comment]
Landing screen wire:
![hwf-landing-20171102](https://user-images.githubusercontent.com/27225981/32323573-61ce2b72-bfc0-11e7-9812-fe0198c0f694.png)

**Comment by ChloeAlper** [comment]
Please have a look at this prototype @stevekeene @TomSteinberg @davidrapson . It's a suggested layout for the Helping Working Families Fund page: https://marvelapp.com/44a0cdb

Things to note:
We can't brighten up the page with examples/case studies this time because this is a new programme, so to break up the text I have suggested including redesigned versions of the diagrams currently included in the programme guidance and an image of a project funded by BLF for a similar amount (500k).

**Comment by ChloeAlper** [comment]
@TomSteinberg @stevekeene please see version 2 landing page:

![hwf-horizontal-tabs-landing-screen](https://user-images.githubusercontent.com/27225981/32451503-da47c828-c30e-11e7-8f1e-293c3b3c4701.png)

**Comment by ChloeAlper** [comment]
Please have a look at the following prototype @TomSteinberg @stevekeene  https://marvelapp.com/3ag89d1/screen/34486886
Are you happy for me to send it to the Welsh team?

**Comment by ChloeAlper** [comment]
@stevekeene @TomSteinberg do these bilingual tabs look ok?

![tab1](https://user-images.githubusercontent.com/27225981/32559022-15063630-c49e-11e7-914a-d5d72c1e7b8d.png)
![tab2](https://user-images.githubusercontent.com/27225981/32559101-3f54d626-c49e-11e7-9fc3-c4f4ad3bb92a.png)
![tab-3](https://user-images.githubusercontent.com/27225981/32559115-4932fc4a-c49e-11e7-95d1-7586717ed93d.png)
![tab4](https://user-images.githubusercontent.com/27225981/32559184-70a41318-c49e-11e7-87e9-172c5ccc163d.png)

**Comment by mattandrews** [comment]
I think the unselected tabs need to have some colour variance between the English/Welsh (maybe slightly dimmed versions of the blue/pink used on the selected tabs), or possibly a divider of some sort, to make it clearer they're different languages. It looks nice besides this though, a clean solution  to a complex page 👍

**Comment by ChloeAlper** [comment]
@mattandrews thanks, I'll try that.

**Comment by mattandrews** [comment]
Awkward.

**Comment by davidrapson** [comment]
Didn't mean to close this! Got excited

**Comment by ChloeAlper** [comment]
Lol

**Comment by ChloeAlper** [comment]
Do you think this works as a solution @mattandrews ?
![tab-3](https://user-images.githubusercontent.com/27225981/32560703-3fa18c10-c4a2-11e7-8406-177f76b1eadb.png)

**Comment by mattandrews** [comment]
I did wonder about suggesting that earlier – looks good, but is there a risk of inadvertently prioritising English (eg. in bold)?!

**Comment by ChloeAlper** [comment]
Hmmm I'll play around with some more options.

**Comment by ChloeAlper** [comment]
@mattandrews do you think this works as a solution?
Tab 1
![tab-1](https://user-images.githubusercontent.com/27225981/32608018-c0fe3b5e-c552-11e7-9873-a8b1b7a535ce.png)
Tab 3
![tab-3](https://user-images.githubusercontent.com/27225981/32608027-cacaa280-c552-11e7-9cfd-3509d419a431.png)

**Comment by mattandrews** [comment]
Looks good, nice work 👍

**Comment by ChloeAlper** [comment]
@stevekeene @TomSteinberg could you check you are happy with the bilingual tab nav here: https://marvelapp.com/116db9bg/screen/34626735 I've stitched the pages together so that you can imagine in action.

**Comment by ChloeAlper** [comment]
Please have a look at the following English pages designs @stevekeene @TomSteinberg 
![hwf-tab1](https://user-images.githubusercontent.com/27225981/32952181-512a446e-cba4-11e7-9643-a8891208e075.png)

![hwf-tab2](https://user-images.githubusercontent.com/27225981/32952233-82a62864-cba4-11e7-9354-c85c80d4e844.png)

![hwf-tab3](https://user-images.githubusercontent.com/27225981/32952248-87445f26-cba4-11e7-9010-43af1e488e7e.png)

![hwf-tab4](https://user-images.githubusercontent.com/27225981/32952252-8c4f5ed0-cba4-11e7-8c41-a60fef8e3f6b.png)

**Comment by ChloeAlper** [comment]
@stevekeene @TomSteinberg please see Welsh pages below:
![hwf-welsh-tab-1](https://user-images.githubusercontent.com/27225981/33009996-afb570ac-cdd0-11e7-8455-762dd6268a2f.png)
![hwf-welsh-tab-2](https://user-images.githubusercontent.com/27225981/33010012-c56dd77c-cdd0-11e7-96ff-53c87427ee72.png)
![hwf-welsh-tab-3](https://user-images.githubusercontent.com/27225981/33010015-c7a0d65c-cdd0-11e7-899b-0fe19a50a0bc.png)
![Uploading HWF-Welsh-tab-4.png…]()

**Comment by ChloeAlper** [comment]
@davidrapson @TomSteinberg @stevekeene please see mobile design below:
![hwf-english-tab1](https://user-images.githubusercontent.com/27225981/33029083-9190c36c-ce0f-11e7-9823-1ac661d3bc3b.png)

**Comment by davidrapson** [comment]
And we're live! https://www.biglotteryfund.org.uk/helping-working-families
