### ISSUE TITLE
Design a case study template in the new style and implement for a real case study

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#279]
- [x] Add a quote block (quote text, attribution) to flexible content
- [x] Add a "More Information" panel to the CMS for Case Studies to be displayed underneath story
- [x] Allow embedding a case study in other places (programme pages)
- [x] Add "Project Story" heading and badge (alongside active project if applicable) to grant detail page
- [x] Update places currently using case studies to link to the correct place (strategics, 10k pages, a few programmes)
- [ ] Prune the list

**Comment by mattandrews** [comment]
See https://github.com/biglotteryfund/blf-alpha/issues/91

**Comment by mattandrews** [comment]
- [ ] Add "Project Story" heading and badge (alongside active project if applicable) to grant detail page
- [ ] Add a "More Information" panel to the CMS for Case Studies to be displayed underneath story
- [ ] Allow embedding a case study in other places (programme pages)
