### ISSUE TITLE
Get Engagement team initial approval for wireframe design of page 19 - Homepage

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#28]
Suggestion - first version(s) of this should be wireframes, not photoshop work

**Comment by ChloeAlper** [comment]
Here's a preliminary stab at page layout. Please have a look @TomSteinberg @stevekeene @mattandrews 
![home-wire-20170522](https://cloud.githubusercontent.com/assets/27225981/26326896/2e644160-3f35-11e7-876d-eb04a2a10707.png)

**Comment by ChloeAlper** [comment]
Here is an updated version of the home page wireframe

![home-wire-20170530](https://cloud.githubusercontent.com/assets/27225981/26592114/b6139f16-4557-11e7-986a-40d8bb2451ed.png)

![home-page-20170530](https://cloud.githubusercontent.com/assets/27225981/26592125/bb03db44-4557-11e7-9e5f-27c8d925b87f.png)

**Comment by ChloeAlper** [comment]
Please see updated home page wireframe @TomSteinberg @stevekeene @mattandrews 
![home-page-wire-20170531](https://cloud.githubusercontent.com/assets/27225981/26717111/11099330-4774-11e7-8624-a8561e684989.png)

![annotated-home-page-wire-20170531](https://cloud.githubusercontent.com/assets/27225981/26717118/16770b5e-4774-11e7-9302-4ee0d04ab3e9.png)

**Comment by ChloeAlper** [comment]
Annotated wireframe:
![annotated-home-page-wireframe-20170602](https://cloud.githubusercontent.com/assets/27225981/26732858/f4c9a5f6-47b0-11e7-9be3-d7fcf99c7049.png)

**Comment by ChloeAlper** [comment]
Annotated wireframe (socials dates corrected):
![annotated-home-page-wireframe-20170602-2](https://cloud.githubusercontent.com/assets/27225981/26733241/17f26698-47b2-11e7-9f33-589ec203c38d.png)
