### ISSUE TITLE
Design page (20) '10K and below'

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#29]

**Comment by ChloeAlper** [comment]
![under 10k page requirements](https://cloud.githubusercontent.com/assets/27225981/26581898/b93e0558-4536-11e7-81bd-ed5b376bd59f.JPG)

**Comment by ChloeAlper** [comment]
Annotated wireframe:
![annotated-under-10k-wireframe-20170602](https://cloud.githubusercontent.com/assets/27225981/26732809/d15d4f3c-47b0-11e7-936c-c1cae8fe918a.png)
