### ISSUE TITLE
Model form abstractions for complex data capture

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#295]
We need a way to create multi-page forms with interdependent fields (eg. selecting some field will show/hide another). This must be accessible to all users. Validation should happen on both client and server-side.

To consider: is JavaScript a requirement? How does GDS manage this? Can we prototype a multi-page form with toggleable fields that works without JavaScript? What about translations?

**Comment by davidrapson** [comment]
I've put together a prototype in https://github.com/biglotteryfund/blf-alpha/pull/300

**Summary**

The main goal of the prototype is to render a simple progressively-enhanced GDS-inspired multi-page form with conditional fields and a focus on a solid UX with comprehensive error handling and messaging. Secondary is to explore a way of modelling multi-page forms such that we don't need to manually code individual fields and can define steps and questions in a schema.

I _think_ the prototype I've put together goes some way to establishing a likely approach for how we might model forms.
