### ISSUE TITLE
Design, build and launch page #21 '10K and above'

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#30]

**Comment by ChloeAlper** [comment]
![over 10k page requirements](https://cloud.githubusercontent.com/assets/27225981/26582037/57defce4-4537-11e7-9afa-fb86f97bdb01.JPG)

**Comment by ChloeAlper** [comment]
Wireframe for the 10k and above page attached @TomSteinberg @stevekeene @mattandrews 
![above-10k-wire-20170612](https://user-images.githubusercontent.com/27225981/27038843-15cdef2a-4f84-11e7-9d6d-20756a66c0d6.png)

**Comment by stevekeene** [comment]
Looks good! It would be good to have a button/link to the under £10K page too.

**Comment by ChloeAlper** [comment]
Updated version attached 
![above-10k-wire-20170612-2](https://user-images.githubusercontent.com/27225981/27042004-a5ed1c4e-4f8d-11e7-95c4-12d3d906cf3f.png)

**Comment by ChloeAlper** [comment]
Please see design @TomSteinberg @stevekeene :
![above-10k](https://user-images.githubusercontent.com/27225981/27329774-c8818980-55ae-11e7-85a9-13ae4d20efe4.png)

**Comment by ChloeAlper** [comment]
@stevekeene I'm not sure if it's still being worked on but would it be possible to get some copy for this page?

**Comment by ChloeAlper** [comment]
Please see attachment with updated copy @stevekeene 
![above-10k-20170630](https://user-images.githubusercontent.com/27225981/27729283-30ca2a8a-5d7d-11e7-94aa-33e7b7963c9f.png)

**Comment by ChloeAlper** [comment]
Copy updated attached:
![above-10k-20170630-2](https://user-images.githubusercontent.com/27225981/27729977-a4064f04-5d7f-11e7-9a84-6fc6fe9f564d.png)

**Comment by ChloeAlper** [comment]
Second copy updated attached:
![above-10k-20170630-3](https://user-images.githubusercontent.com/27225981/27731031-65eaf860-5d83-11e7-9579-500aa76f843c.png)

**Comment by ChloeAlper** [comment]
Does this solve the 'across the uk' button's awkwardness issue @TomSteinberg @stevekeene ?
![screen shot 2017-07-03 at 08 54 12](https://user-images.githubusercontent.com/27225981/27783430-119306fc-5fce-11e7-9056-e5996df02859.png)

**Comment by mattandrews** [comment]
I need a PSD of this (and a mobile version too)! Same goes for #76.

**Comment by ChloeAlper** [comment]
Please see mobile version of this page below @mattandrews @stevekeene 

![above-10k-mobile](https://user-images.githubusercontent.com/27225981/28166350-77345d90-67cf-11e7-9d61-cce37c7442d7.png)

**Comment by stevekeene** [comment]
Looks good to me!

**Comment by ChloeAlper** [comment]
Layout changed, correct images and text now being used:
![screen shot 2017-07-20 at 16 33 35](https://user-images.githubusercontent.com/27225981/28426229-7deb5d1e-6d6a-11e7-8d55-1e6f81362114.png)

**Comment by stevekeene** [comment]
Cruse case study needs a full-stop at the end.

Beneath the country buttons (or elsewhere, but trying to keep consistency with under 10k page) there needs to be a link to under 10k page. Text could be:

"We also offer [funding from £300 to £10,00](url)0 to support what matters to people and communities

**Comment by ChloeAlper** [comment]
Typos corrected and additional line added:
![above-10k](https://user-images.githubusercontent.com/27225981/28525547-8507a6b0-707c-11e7-97e4-321c6934ab56.png)

**Comment by mattandrews** [comment]
Here's what's left for this page:

- [ ] Get all finalised text translated (including case studies)
- [ ] Launch legacy site pages for case studies
- [ ] Make sure user journeys are correct (eg. country selection)
- [ ] Then: follow standard signoff checklist

**Comment by ChloeAlper** [comment]
Please check you are happy with the updated page design @TomSteinberg @stevekeene 

![over-10k-20170929](https://user-images.githubusercontent.com/27225981/31006778-1b21ed60-a4f6-11e7-8831-65e0cc11d9c9.png)

**Comment by stevekeene** [comment]
Happy with design, just one typo in the heading - should be £10,000

**Comment by ChloeAlper** [comment]
Thank you @stevekeene . Typo corrected:
<img width="727" alt="screen shot 2017-09-29 at 09 27 11" src="https://user-images.githubusercontent.com/27225981/31007400-71fc69c4-a4f8-11e7-9b18-a4530d479ea8.png">

**Comment by mattandrews** [comment]
Now live! https://www.biglotteryfund.org.uk/over10k
