### ISSUE TITLE
Design build and launch page #4 - Contact us

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#31]

**Comment by ChloeAlper** [comment]
Please see design @stevekeene @TomSteinberg @mattandrews
![4-contact-us](https://cloud.githubusercontent.com/assets/27225981/26407735/d51eee7e-4093-11e7-8f2f-c6bcd1d9c182.png)

Note: @stevekeene I removed a 'CHECK WHO ANSWERS' line from the last section so I imagine that might still need your attention?

**Comment by ChloeAlper** [comment]
Updated the first generic image as it wasn't sitting so well:

![4-contact-us-20170525](https://cloud.githubusercontent.com/assets/27225981/26442221/765529c4-412b-11e7-9da2-0da97876c81d.png)

**Comment by stevekeene** [comment]
Hi @ChloeAlper - looks really good, and really pleased how each option is clearly separated out. 

I'm wondering if we actually need the stock images for each question? I don't want to ruin the style of the page, but I'm not sure if we need that sort of visual reinforcement, if that makes sense? But happy to discuss!

**Comment by mattandrews** [comment]
My only feedback is that the text in each location block (in the first box, applying for funding) all feels quite tight – maybe some bullet points (or even just bold text like '**Phone**: 0345 4 70 20 30') would help readability?

**Comment by ChloeAlper** [comment]
Updated desktop version attached @stevekeene @mattandrews @TomSteinberg. Changes made: 
• Images changed
• text given more space, treatment altered

![4-contact-us-20170525-2](https://cloud.githubusercontent.com/assets/27225981/26456210/4ed57c62-4164-11e7-8126-27838297202a.png)

**Comment by stevekeene** [comment]
Looks good, thanks @ChloeAlper - I'm happy with this!

**Comment by mattandrews** [comment]
Looks awesome ✉️ ☎️ 📠 🐦

**Comment by stevekeene** [comment]
Phone numbers checked and seem to be fine!

**Comment by TomSteinberg** [comment]
Thanks Steve, you are an 👼

**Comment by ChloeAlper** [comment]
@mattandrews please see handover doc attached 
![4-contact-us-annotations](https://cloud.githubusercontent.com/assets/27225981/26580124/aaa8a848-452e-11e7-8b34-c0d5d21a7e90.png)

**Comment by ChloeAlper** [comment]
Please see mobile version of this page @mattandrews @TomSteinberg @stevekeene 
![4-contact-us-mobile](https://cloud.githubusercontent.com/assets/27225981/26683712/a7a392b6-46dc-11e7-9f0d-5f9642461992.png)

**Comment by mattandrews** [comment]
Now fixed on live: https://www.biglotteryfund.org.uk/contact
![image](https://cloud.githubusercontent.com/assets/394376/26719166/5f20b61e-477b-11e7-859c-a47b2f3dc2a9.png)

Note that the text runs full width rather than inline, this is related to the issues in the past with mobile screens chopping this block text off at weird places etc.

Also – I'm using this same component ("segment") on the Press Coverage page too so this has the same effect there, eg:

![image](https://cloud.githubusercontent.com/assets/394376/26719204/86f9e2c8-477b-11e7-86b7-ed93ace99789.png)
