### ISSUE TITLE
Work out which pages to replace in order to maximise the number of visitors who never see a legacy page

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#316]
This is for two purposes:

1 - To help us prioritise in future sprint meetings
2 - To help us to understand how we are progressing towards a state where 95% of visitors never see a legacy page.

**Comment by davidrapson** [comment]
Added some notes to our Data & Metrics document which covers the main findings.

**Comment by davidrapson** [comment]
Updated our Data & Metrics docs with some additional findings including a graph showing potential impact of replacing top 10, 25, 50, 100, and 250 trafficked pages.
