### ISSUE TITLE
Redirect every funding finder results page to a page hosted on the new CMS

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#318]
Redirect every funding finder results page to a page hosted on the new CMS

- https://www.biglotteryfund.org.uk/funding/funding-finder
- https://www.biglotteryfund.org.uk/welsh/funding/funding-finder
- https://www.biglotteryfund.org.uk/Home/Funding/Funding%20Finder
- https://www.biglotteryfund.org.uk/home/funding/funding-finder

Redirect to: https://www.biglotteryfund.org.uk/funding/programmes

## Discussions to have

- [x] Talk to Nic
- [x] Talk to Engagement

## Development Tasks

- [x] Review analytics data to establish primary URLs funding finder is accessed from
- [x] Add redirects for common URL params to equivalents on new page.
- [x] Redirect everything else to full programmes list
- [x] Handle normalising legacy query strings, notably `&amp;` in URLs.
- [x]  Handle closed programmes
- [x] Test in live-equivalent environment to confirm redirects work as expected
- [x] Deploy redirects to test environment

## Launch tasks  

- [x] Set routes for `/Home/Funding/Funding%20Finder` redirects to `live`. Deploy and test redirects.
- [x] Set routes for `/funding/funding-finder` redirects to `live`. Deploy and test redirects.
- [x] Monitor redirects for any 404s

**Comment by davidrapson** [comment]
Initial experiments around doing this here: https://github.com/biglotteryfund/blf-alpha/pull/448
