### ISSUE TITLE
Design build and launch #7 - Jobs

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#32]

**Comment by ChloeAlper** [comment]
Please see design attached @stevekeene @TomSteinberg @mattandrews:
![7-jobs-at-the-big-lottery-fund](https://cloud.githubusercontent.com/assets/27225981/26786994/54b2582c-4a00-11e7-89e1-87f010ebc2e3.png)

**Comment by mattandrews** [comment]
Looks great to me. Where can I apply?!

**Comment by TomSteinberg** [comment]
Looks good @ChloeAlper !

**Comment by ChloeAlper** [comment]
Mobile version attached @stevekeene @TomSteinberg @mattandrews :
![7-jobs-at-the-big-lottery-fund-mobile](https://cloud.githubusercontent.com/assets/27225981/26823278/f48f1f7a-4aa4-11e7-9b5d-72401e97f3e4.png)

**Comment by ChloeAlper** [comment]
Slight tweak to the mobile version. Changes made:
• Improved rounding on button 
• Reduced padding
![7-jobs-at-the-big-lottery-fund-mobile](https://user-images.githubusercontent.com/27225981/26837657-e6cb1c50-4ad5-11e7-83d4-57c1c6e6e212.png)
Please let us know whether you are happy for this mobile page to be built @stevekeene @TomSteinberg

**Comment by stevekeene** [comment]
All looks good to me, thank you!

**Comment by TomSteinberg** [comment]
👍

**Comment by ChloeAlper** [comment]
Handover docs attached @mattandrews 

![7-jobs-at-the-big-lottery-fund-handover](https://user-images.githubusercontent.com/27225981/26870401-c9f5cd2c-4b67-11e7-9714-21f6e77dbec3.png)

![7-jobs-at-the-big-lottery-fund-mobile-handover](https://user-images.githubusercontent.com/27225981/26870405-cd409fd4-4b67-11e7-9902-1a140900f05f.png)

**Comment by mattandrews** [comment]
@ChloeAlper This is ready for review on the TEST site 👍

**Comment by mattandrews** [comment]
Now live!
