### ISSUE TITLE
Add extra CMS field to separate 'pink box' text on programme pages from the trail text used on listings

### ISSUE THREAD

**Issue by LynseyJReynolds** [biglotteryfund/blf-alpha#3302]
We've had to turn off the programme descriptions on the open programme list - https://www.tnlcommunityfund.org.uk/funding/programmes

This reduces the information that customers need to allow them to choose which programme to find out more about.

By introducing a new field in the cms that acts as trail text (but is completely separate to the content in the pink box) we should be able to turn the descriptions back on.

**Comment by mattandrews** [comment]
This is now live!
