### ISSUE TITLE
Tech-debt: Review sessions config to avoid unwanted cache sharding.

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#333]

**Comment by mattandrews** [comment]
Is this done now @davidrapson?

**Comment by davidrapson** [comment]
Sort of. We _avoided_ the problem by changing the ebulltin submission URL, but the use of the `flash` middleware still means session IDs can get set earlier than desired. Still need to do a little work here.

**Comment by davidrapson** [comment]
This is fixed now, reworked how flash is used on the session is only initialised when it is really needed.
