### ISSUE TITLE
Allow programme info on past grants pages to use trail text

### ISSUE THREAD

**Issue by LynseyJReynolds** [biglotteryfund/blf-alpha#3344]
Our past grants entries e.g. https://www.tnlcommunityfund.org.uk/funding/grants/0020110695 contain information about the programme that the grant was funded under.

The programme description info is pulled from the pink box in the programme pages. Due to COVID-19 related content changes, a lot more copy has been put into these boxes and it's no longer viable to include it all in the past grants pages.

We've introduced trail text which acts separately from the pink box which can be used instead.

**Comment by mattandrews** [comment]
Now fixed/live!
