### ISSUE TITLE
Tech-debt: Synchronise database as a more explicit step

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#335]
Refactor `bin/www` to avoid syncing database? Can we directly require `server.js` in tests instead?

**Comment by mattandrews** [comment]
Also handle migrations properly (which is really what this ticket is about).

**Comment by davidrapson** [comment]
Given with our move to `cypress` for tests we changed how we start instances of the app for tests I'm not sure this is still a problem. Closing this,
