### ISSUE TITLE
Rework about section to use flexible-content-next

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#3361]
Currently the about section uses an older flexible content template. This should be restructured so it can use the `flexible-content-page` template, and behave like the newer Funding structure in the CMS.

**Comment by mattandrews** [comment]
This is now done and I'm super happy about it! Next step is to clean up the old sections/fields.

**Comment by mattandrews** [comment]
This is now done and I'm super happy about it! Next step is to clean up the old sectio
