### ISSUE TITLE
Move jobs pages to the about section

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#3362]
Connected to https://github.com/biglotteryfund/blf-alpha/issues/3361

Currently the jobs and benefits pages are handled as one-off singles. These should be moved to the about section once it's using flexible-content-page,  this will let us remove the one-off router code in server.js

```js
jobs: {
   path: '/jobs*',
   router: basicContent(),
}
```

**Comment by mattandrews** [comment]
Now done – these pages live in the About section.
