### ISSUE TITLE
Deprecate Funding Guidance structure in the CMS

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#3365]
We currently have a Funding structure (all new funding pages) and an older Funding Guidance structure in the CMS. Many of the pages in Funding Guidance have already been migrated to the newer structure so could be archived but for any remaining pages can we migrate them over and deprecate the Funding Guidance structure?

Allows us to remove this code in the funding router:

```js
router.use('/funding-guidance/*', basicContent());
```

**Comment by mattandrews** [comment]
This is now done, yay! Just the Contact and Data page left to go...
