### ISSUE TITLE
Move the our people section to About structure? 

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#3366]
Dependant on https://github.com/biglotteryfund/blf-alpha/issues/3361

Can we move the our people section to About structure? Add "profile" type to flexible content perhaps. Allows us to remove special case code from the app.

Limitations of the profile pages can already be seen here https://www.tnlcommunityfund.org.uk/about/our-people/advisory-group-membership

**Comment by mattandrews** [comment]
This is now done!
