### ISSUE TITLE
Deprecate listing-page and information-page templates

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#3367]
Deprecate listing-page and information-page templates (essentially anything using `basicContent`). Migrate everything to flexible-content-page. We log usage of these templates so it's possible to see a list of the most visited pages using these templates to prioritise which ones to tackle first.

**Comment by mattandrews** [comment]
There's [a list here in DataDog](https://app.datadoghq.com/logs/analytics?agg_q=%40url&cols=service%2Cstatus%2C%40applicationStatus&from_ts=1586951955799&index=&live=true&messageDisplay=expanded-lg&query=Legacy%20content%20type&stream_sort=desc&to_ts=1589543955799&top_n=100&viz=toplist) showing the URLs of pages using these routers.

**Comment by mattandrews** [comment]
Just closed off most of these in https://github.com/biglotteryfund/blf-alpha/issues/3361 but there are a few that remain (Contact, Funding Guidance) which I can do next.
