### ISSUE TITLE
Fix incorrectly scoped copy in publication search

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#3370]
The publications search section uses copy from the locale file from `insights.documents` (see `publication-search.njk`).  Should be corrected so that copy is not scoped to a separate section. Either duplicate the bits of copy that are needed, or rename the original key to make it clear that it's shared.

**Comment by mattandrews** [comment]
I think renaming the key makes the most sense here as the majority of it is generic "search"-related terms.
