### ISSUE TITLE
Consider migrating away from query-string

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#3381]
The [query-string](https://github.com/sindresorhus/query-string) library is currently locked to an older version because the latest version only officially supports the latest version of Chrome, Firefox, and Safari.

This module is only used on the past grants search and free materials form, it might be worth migrating to the native [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) (with a [polyfill for IE](https://github.com/zloirock/core-js#url-and-urlsearchparams))

**Comment by mattandrews** [comment]
This is simple enough for the free materials form but the past grants search makes core use of `this.filters` (which is the `query-string` object) which would need a bit more attention when testing changes etc.
