### ISSUE TITLE
Prevent the min and max values from programme pages from being displayed

### ISSUE THREAD

**Issue by LynseyJReynolds** [biglotteryfund/blf-alpha#3383]
Currently, if there's no 'funding size description' entered for a programme page on the cms, it will display the 'Minimum funding size' and 'Maximum funding size'.

It's sometimes necessary to use dummy figures in those boxes to change which programme lists they appear in.

We need to prevent the min and max funding size input from displaying to the public so that we can use them behind the scenes.

When the 'funding size description' is empty, we should display nothing.

**Comment by LynseyJReynolds** [comment]
<img width="590" alt="Screenshot 2020-05-19 at 10 35 33" src="https://user-images.githubusercontent.com/14089243/82310867-d71b1880-99bc-11ea-9fd1-96d854b9d9ed.png">

**Comment by mattandrews** [comment]
Fixed in https://github.com/biglotteryfund/blf-alpha/pull/3396
