### ISSUE TITLE
Enable child page lists to work in draft and pending

### ISSUE THREAD

**Issue by LynseyJReynolds** [biglotteryfund/blf-alpha#3384]
Currently drafts that include child page lists won't display correctly until they are published.

Investigate whether we can provide a more realistic preview experience with draft and pending pages.

**Comment by mattandrews** [comment]
Here's my progress on this: https://craftcms.stackexchange.com/questions/35858/how-can-i-fetch-an-entrys-draft-children 

(eg. it's not clear if it's even possible to look up unpublished draft child entries)
