### ISSUE TITLE
Test single bundle in favour of code-splitting for client-side code

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#3394]
The client-side code is currently code-split, so that we load multiple bundles but we're not getting that much value out of doing it (our overall bundle size isn't _that_ big). We also get bundle loading errors with relative frequency.

Suggest testing testing a single bundle in place of code-splitting as long.

In the process also suggest removing `SentryVue`, it adds a fair chunk to the build size and doesn't actually help with capturing errors (if anything it's more confusing).

**Comment by mattandrews** [comment]
Had a go at this and the overall bundle size grew to around 450kb, which caused Webpack to throw a warning. This isn't necessarily a blocker – the overall bundle when combined together is about this size currently, it's just delivered in separate chunks. But the number of `ChunkLoadError`s we're seeing on Sentry is making me keen to consider dropping the code-splitting.

One alternative could be to "manually" code-split: eg. compile the Vue-related forms code into its own file and only load it on those pages – it's more than half the bundle size alone.

**Comment by mattandrews** [comment]
After trying a few solutions to split the bundle differently, it all comes down to the same thing: slower connections will see the final chunk(s) fail to load. Our only option in that case is to detect this and trigger a full-page reload (not very nice UX and not even required given we don't depend on JS for anything), or to simply ignore the error in Sentry. I've opted for the latter.
