### ISSUE TITLE
Upgrade vue-i18n to latest version

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#3404]
Originally held off on upgrading `vue-i18n` as there was a regression with IE11 support in a previous version. From the looks of the change-log they've done some work to sure up their browser support and fixed the issues, so worth upgrading and testing again.

Can be done via local tunnel using our browser testing service. The budget component in the under £10,000 form is the best one to test against.

**Comment by mattandrews** [comment]
This is done!
