### ISSUE TITLE
Change 'talk to us' link in the footer to 'contact us'

### ISSUE THREAD

**Issue by LynseyJReynolds** [biglotteryfund/blf-alpha#3528]
We recently changed our contact page from 'talk to us' to 'contact us' but didn't change the link in the footer to match the new page title.

**Comment by LynseyJReynolds** [comment]
<img width="268" alt="Screenshot 2020-07-08 at 13 06 05" src="https://user-images.githubusercontent.com/14089243/86916644-d0d32e00-c11b-11ea-9ac9-7a80aa3d3f0b.png">

**Comment by mattandrews** [comment]
Now live!
