### ISSUE TITLE
Build high contrast stylesheet switcher and implement across all new pages

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#36]
WCAG analysis tells us that header contrast isn't high enough, so we're going to need to copy other best practice in order not to drop the brand's blue shade

**Comment by ChloeAlper** [comment]
Does this work as a skip nav @mattandrews?
![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-skip-nav](https://cloud.githubusercontent.com/assets/27225981/25956505/d2a48e18-3663-11e7-8e81-5781aa2cd4c8.png)

**Comment by mattandrews** [comment]
Yep, looks good.

Could we add a "Content" or "Skip to content" button in there, to mimic the existing one? Just jumps the user down to the main content area (so they don't have to tab through the header etc).

**Comment by ChloeAlper** [comment]
Skip to content button added. Please see skip nav attached @TomSteinberg @mattandrews @stevekeene:

![1-how-to-tell-people-about-your-lottery-funding-using-our-logo-skip-nav-2](https://cloud.githubusercontent.com/assets/27225981/25959741/96b1e762-366c-11e7-8fbe-4d837629f1ea.png)
