### ISSUE TITLE
Investigate methods to reduce time taken for blue/green deploys

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#375]

**Comment by mattandrews** [comment]
Looked into Packer: it looks like it could shave about 45 seconds off the install time when spinning up a deploy, but it still seems like CodeDeploy is equally slow to provision a new EC2 instance regardless of whether that instance has our dependencies or not. 

Might be worth looking into whether this is a CodeDeploy thing (eg. could we spin up a demo Elastic Beanstalk version of the website app and try that?) or just the reality of EC2 timings.
