### ISSUE TITLE
Implement micro-survey on new homepage

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#383]
Work with design colleagues to ensure that:

a) It isn't shown to more people than necessary
b) That isn't an annoying and offputting popup
c) That it only shows as a time when feedback is likely to be offered (e.g a few seconds in)
d) That we have a calendar event to remove it!

**Comment by mattandrews** [comment]
@TomSteinberg what question are we asking on this survey? The same as the others (eg. "Did you find what you were looking for?") or something more tailored?

**Comment by mattandrews** [comment]
We could also drive this from the CMS (at the moment it requires a code change to deploy new surveys)

**Comment by mattandrews** [comment]
Now live!
