### ISSUE TITLE
Build prototype of 'Submit Your Idea' Tool for Reaching Communities

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#385]
Includes:
- Design and implement user interface
- Design and implement mechanism for securely storing submitted ideas
- Design and implement connection with demo CRM deployment
- Perform penetration testing

**Comment by davidrapson** [comment]
Marking this as done. We went for a lighter-weight approach which doesn't send data anywhere (yet), but is available for user-testing at https://test.blf.digital/experimental/apply/your-idea
