### ISSUE TITLE
Tidy up font list for style-guide

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#389]
- [x] Rename classes to match new document (can you upload this here @ChloeAlper?)
- [x] Review small-screen breakpoints for font-scales and adjust if needed

**Comment by ChloeAlper** [comment]
Here's what I've done so far:
![typography](https://user-images.githubusercontent.com/27225981/32777332-ab357b96-c92d-11e7-8b09-7d5675feb1f0.png)
The mobile values are missing I'm afraid

**Comment by davidrapson** [comment]
What might be worthwhile is if I try swapping these out now and we could review the mobile values in a browser once that's done. Would that work?

**Comment by mattandrews** [comment]
Think this is done – @ChloeAlper, happy to close?

Main change here is that the type styles no longer have mobile overrides – that okay?

**Comment by ChloeAlper** [comment]
I think we will need to work on some mobile overrides but I don't have time to look at it at the moment annoyingly

**Comment by mattandrews** [comment]
Closing due to lack of movement.
