### ISSUE TITLE
Experiment with connecting to CRM API

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#393]

**Comment by davidrapson** [comment]
Downgraded this to "Experiment with connecting to CRM API" as we are more interested in just validating that we can _connect_ to some kind of API and that it looks useful rather than doing anything further at this point.

**Comment by davidrapson** [comment]
Did some initial experimentation to confirm we can authenticate with the CRM's API and do something useful with it. Have shared some notes with the rest of the team.
