### ISSUE TITLE
Make the up and down arrows on the survey interactive

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#420]
The close icon responds when you mouse over it but the up and down arrows don't. Could we make the up and down arrows feel similarly alive?

<img width="512" alt="screen_shot_2017-11-15_at_16 41 22_1024" src="https://user-images.githubusercontent.com/27225981/33261872-3980517c-d35c-11e7-92e1-f823ea7ad45c.png">

**Comment by mattandrews** [comment]
@ChloeAlper how's this?

![anim](https://user-images.githubusercontent.com/394376/33318163-8ef3e47c-d431-11e7-9f89-ee203f72c21d.gif)

(Just made it switch to `#cacaca` on hover)

**Comment by ChloeAlper** [comment]
It looks great!

**Comment by mattandrews** [comment]
Cool – done!
