### ISSUE TITLE
Add "East Africa Disability Fund' to 'above 10k'

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#426]

**Comment by mattandrews** [comment]
So I think this needs some help from @ChloeAlper – the issue is these buttons:

![image](https://user-images.githubusercontent.com/394376/33315589-03e0bb42-d429-11e7-98b5-7ee391da4790.png)

Basically, we need an option for "Outside UK" or similar, which will link through to this project (and potentially others in future). Any thoughts?

**Comment by davidrapson** [comment]
This fund is no longer open so closing this.
