### ISSUE TITLE
Change logos on pages that offer Wales-specific products

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#427]

**Comment by mattandrews** [comment]
@TomSteinberg do we have a list of the pages for this, or do we need to speak to Dave? Presumably the logos and free materials pages are on the list as they're both offering bilingual "products"?

**Comment by davidrapson** [comment]
Contacted Dave in the first instance.

**Comment by mattandrews** [comment]
This is now done (any programme located in Wales automatically gets the bilingual logo)
