### ISSUE TITLE
Ensure colour palette aligns with new brand guidelines

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#43]
Update hex values to match those in the brand guidelines sent on 16.05.17

**Comment by mattandrews** [comment]
Fixed in 3edc179bd40903f9ce8e4aaee554d78e4b96d02e:

![image](https://cloud.githubusercontent.com/assets/394376/26448054/45b5f3da-4143-11e7-971f-579b9f9415c9.png)

(turns out we were already using the correct blue!)
