### ISSUE TITLE
Remove 'Awarding Funds From...' logo from footer

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#44]
The 'Awarding Funds From...' logo has been discontinued and needs to be removed from the footer.

**Comment by mattandrews** [comment]
Fixed in 6997e772822d7db4133b3de75c3249b6d947330e:

![image](https://cloud.githubusercontent.com/assets/394376/26447948/d109915e-4142-11e7-9211-3e8342d3fa4f.png)
