### ISSUE TITLE
Change header on page #1 to say "National Lottery" rather than "lottery"

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#45]
The header over the main image currently says "How to tell people about your lottery funding using our logo"

We need to change that to ""How to tell people about your National Lottery funding using our logo"

**Comment by mattandrews** [comment]
Fixed in 83af08a0bd1ebddeba4f8c5bb0c9703b448b041a:

English:
![image](https://cloud.githubusercontent.com/assets/394376/26447971/eb5d2c0a-4142-11e7-8ce9-0706f2059571.png)

Welsh:
![image](https://cloud.githubusercontent.com/assets/394376/26447985/fbfbd200-4142-11e7-8c93-09ba019bd10e.png)
