### ISSUE TITLE
Change text on 'managing funding' page (2), within the box that covers displaying the logo 

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#46]
The bottom-left, light-blue box that points to the logos page currently says:

Display the "Lottery Funded" logo in various appropriate places

It now needs to say:

Display the "National Lottery Funded" logo in various appropriate places

**Comment by mattandrews** [comment]
Fixed in 8dd4f83258a319cbe13690a5e004118a77096fd6:

English:
![image](https://cloud.githubusercontent.com/assets/394376/26448030/28c749a4-4143-11e7-81fb-1e7014c90fc4.png)


Welsh:
![image](https://cloud.githubusercontent.com/assets/394376/26448024/1fa54ec0-4143-11e7-9ab0-f770eb6e52d3.png)
