### ISSUE TITLE
Refine padding and placement of Welsh and English logos

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#49]
The Welsh logo could be larger and the padding below it is too generous.
English logo is a good size but we could reduce the padding beneath it.

**Comment by mattandrews** [comment]
Fixed in 4f946878a437872084de12578e7bf00f89b5f23d:

English:
![image](https://cloud.githubusercontent.com/assets/394376/26448082/5c1e424e-4143-11e7-9894-be805c0256f9.png)

Welsh:
![image](https://cloud.githubusercontent.com/assets/394376/26448089/66e40a7e-4143-11e7-9573-91b115998b6f.png)
