### ISSUE TITLE
Chrome M70 (March-October 2018) Symantec update

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#495]
Acronyms FTW.

https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html

**Comment by mattandrews** [comment]
Amazon seem to be on this: https://forums.aws.amazon.com/thread.jspa?messageID=820290 and

**Comment by davidrapson** [comment]
Message from AWS support on the linked forum thread noting that they are in the process up migrating certs which will be completed by the end of January. Will keep an eye on this thread and contact AWS support through our account if there's no movement.

**Comment by davidrapson** [comment]
Certs are scheduled to be updated between 8 January 2018 and 22 January 2018

**Comment by davidrapson** [comment]
Regardless of Amazon's progress we've bypassed this step by no longer directly using any raw CloudFront domains. We use media.biglotteryfund.org.uk now.
