### ISSUE TITLE
Implement warning on merch ordering page (3) that you can't order more than one plaque 

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#50]

**Comment by mattandrews** [comment]
Is this still valid, @stevekeene? At the moment the code enforces it (but doesn't explain why it's blocked)...

**Comment by stevekeene** [comment]
@mattandrews We're happy now for people to order one of each (we're trying to get rid of old stock anyway). This might be something we revisit later in the year, depending on users/stock etc.

**Comment by mattandrews** [comment]
Great! Will close.
