### ISSUE TITLE
Redirect two NLAFA URLs

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#500]
Redirect the following URLs...

1 - https://www.biglotteryfund.org.uk/funding/Awards-For-All  
2 - https://www.biglotteryfund.org.uk/awardsforall

  So they both point to...

https://www.biglotteryfund.org.uk/under10k

**Comment by mattandrews** [comment]
Now live!

**Comment by TomSteinberg** [comment]
Also please add
1 -  non-caps versions
2 - https://www.biglotteryfund.org.uk/a4a
