### ISSUE TITLE
Add messages to merch ordering page (3) to explain who to phone or email in case of confusion

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#52]
Comes from user testing

**Comment by mattandrews** [comment]
@ChloeAlper is this done with the recent changes?

**Comment by ChloeAlper** [comment]
@stevekeene do you know about this ticket? I don't know what's missing

**Comment by stevekeene** [comment]
@ChloeAlper I think we just need to add something to the successful order pop-up message - along the lines of "If you have any questions or queries about your order please [get in touch with our branding team](branding@biglotteryfund.org.uk)."

**Comment by ChloeAlper** [comment]
Please see proposed treatment below @mattandrews @stevekeene 

![screen shot 2017-07-20 at 12 28 22](https://user-images.githubusercontent.com/27225981/28415325-0cb09510-6d47-11e7-9672-de29d2bb077f.png)

**Comment by stevekeene** [comment]
Perfect, thank you.

**Comment by mattandrews** [comment]
Now live!
