### ISSUE TITLE
CMS formatting considerations

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#539]
- [ ] How to add anchor links?
- [ ] Formatting of inline images (crops / max-widths etc.)
- [ ] How to format buttons without needing to edit HTML

**Comment by mattandrews** [comment]
- `width` attributes are stripped from images 
- `&nbsp;` is preserved and does weird things to linebreaks

**Comment by davidrapson** [comment]
Merged into https://github.com/biglotteryfund/blf-alpha/issues/694
