### ISSUE TITLE
Reduce weight of pages by avoiding download of webfont for menu use

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#54]

**Comment by mattandrews** [comment]
We can probably just directly embed the four (so far) webfont icons we're using:

- search
- left arrow
- right arrow
- x/close icon

**Comment by TomSteinberg** [comment]
Would be lovely to know what difference this made!

**Comment by mattandrews** [comment]
Just did a quick comparison:

|             | Before | After | Change |
|-------------|--------|-------|--------|
| Page weight | 628kb  | 511kb | -18%   |
| Load time   | 497ms  | 417ms | -16%   |

**Comment by TomSteinberg** [comment]
👍  🚀
