### ISSUE TITLE
Increase padding beneath text in all bounded text boxes 

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#56]
Text boxes are looking a little tight. Please increase padding below text to 40px across all pages
![screen shot 2017-05-23 at 09 57 34](https://cloud.githubusercontent.com/assets/27225981/26346504/51854cc0-3f9e-11e7-9c88-4f4c1d97405d.png)

**Comment by mattandrews** [comment]
Fixed in 24beb11ef6cc4f324dbe4e19cdc0be5784296998

![image](https://cloud.githubusercontent.com/assets/394376/26448127/989a38d6-4143-11e7-9713-576d8dbef8c0.png)
