### ISSUE TITLE
Small improvements to form page (3)

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#57]
- [x]  Form input text colour should go to `#333333` when complete
- [x]  Background behind quantity count should stay white
- [x]  Increase the gap between entry fields
- [x]  Add white box behind item counter
- [x]  Increase padding above section titles
- [x] Centre plus/minus
- [x] Close gap beneath short products
- [x] Place the short products at ends of the rows

**Comment by ChloeAlper** [comment]
Please increase the gap between entry fields to 30px (as per design) so that there is a bit more breathing space on the page. 
![screen shot 2017-05-23 at 14 08 04](https://cloud.githubusercontent.com/assets/27225981/26355624/4886be24-3fc1-11e7-98f2-5bf9959ec02a.png)

**Comment by ChloeAlper** [comment]
Please reinsert white box behind item counter when item has been highlighted/selected 
![screen shot 2017-05-23 at 14 10 25](https://cloud.githubusercontent.com/assets/27225981/26355743/bf90d3ba-3fc1-11e7-9222-30b1c34f954e.png)

**Comment by ChloeAlper** [comment]
Please insert 40px padding above page section headings 
![screen shot 2017-05-23 at 14 19 27](https://cloud.githubusercontent.com/assets/27225981/26356113/eb79a6fe-3fc2-11e7-8c1b-7e370567c823.png)

**Comment by ChloeAlper** [comment]
Is it possible to hide grey line breaks when an item is highlighted through selection? I think that doing so will make things look tidier. 

![screen shot 2017-05-23 at 14 30 25](https://cloud.githubusercontent.com/assets/27225981/26356635/9b786e9a-3fc4-11e7-8e9d-aa1be0f06980.png)

**Comment by ChloeAlper** [comment]
I'm not sure what consensus is (please respond with your thoughts @mattandrews @TomSteinberg @stevekeene) but I feel as though the 'Submit' button at the bottom of the form shouldn't change to clickable blue until the user has successfully selected products AND completed the form (at the moment it changes after user has successfully selected a product)

**Comment by ChloeAlper** [comment]
Please centre plus and minus icons within their button boxes so that they are aligned (they look like they need to shift 1px up) 
![screen shot 2017-05-23 at 15 02 52](https://cloud.githubusercontent.com/assets/27225981/26358015/11d8182a-3fc9-11e7-832e-7ace29102215.png)

**Comment by ChloeAlper** [comment]
Please close gap beneath 'Vinyl banner (pink)''s product image. Please then place the shorter products at ends of the rows so that the eye has less cause to jump
![screen shot 2017-05-23 at 15 22 33](https://cloud.githubusercontent.com/assets/27225981/26358865/c928f812-3fcb-11e7-9fe0-dac68d40c1bf.png)

**Comment by TomSteinberg** [comment]
I'm happy with the idea that the submit button doesn't active until all the required fields have been entered. It's a good clue to users that they missed something.

**Comment by mattandrews** [comment]
Just shipped a fix (to the `TEST` environment) for a bunch of these things in https://github.com/biglotteryfund/blf-alpha/commit/7d6bf19f68eab04231b2a1e56843d566b791b2aa:

- [x] Increased gap between details entry fields
- [x] Reinserted white box behind item quantity counter
- [x] Added 40px padding above headings
- [x] Centered plus/minus icons
- [x] Closed gap on vinyl banner
- [x] Added missing stickers

... the submit button thing sounds great but will take a bit longer to do so I'll raise that as a separate ticket.

The thing about borders above/below selected items is also quite fiddly (you're hovering over the item below the border so it's not trivial to turn the border off the item above, etc) – if it's not something we can live with then can you raise a separate issue for it, @ChloeAlper?

**Comment by ChloeAlper** [comment]
Thanks Matt! I think we can defo live with those borders. Would be nice to have eventually but it's a trivial point.

**Comment by mattandrews** [comment]
Okay to close this issue @ChloeAlper (since we have a new issue now for the submit button: https://github.com/biglotteryfund/blf-alpha/issues/60)?

**Comment by ChloeAlper** [comment]
Fine by me, thanks @mattandrews
