### ISSUE TITLE
Set up a few extra URL redirects

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#58]
~~First, the primarily URL of the Social media page (12) should be a new URL:
https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/social-media~~

~~And the primary URL of the getting press coverage page (18) should be a new URL:
https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/press~~

Then set up the following redirects:

~~From: https://www.biglotteryfund.org.uk/publicity
To: https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding~~

~~From: https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/logodownloads
To: https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/logodownloads~~

~~From: https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials
To: https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials~~

~~From:https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials/bilingual-materials-for-use-in-wales
To: https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials~~
From: https://www.biglotteryfund.org.uk/welsh/funding/funding-guidance/managing-your-funding/ordering-free-materials
To: https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials

**Comment by mattandrews** [comment]
Have done some of these now (crossed off the ones I've done) – with the final Welsh one, will clarify about that.
