### ISSUE TITLE
Tidy coloured highlight bar edges on all pages

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#59]
Please ensure that the edges of the coloured highlight bars that sit on top of context boxes are cut at a right-angle and that they meet the far edges of the boxes they are highlighting. 
![screen shot 2017-05-23 at 15 30 34](https://cloud.githubusercontent.com/assets/27225981/26359276/ec5d89a0-3fcc-11e7-9f0e-3546d5d757bb.png)

**Comment by mattandrews** [comment]
Closing this after chatting with @ChloeAlper due to technical complexity! (eg. see [this question](https://stackoverflow.com/questions/7261703/set-css-border-to-end-in-a-90-instead-of-a-45-degree-angle))
