### ISSUE TITLE
Use a picture that isn't of someone in a school

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#6]
... because we don't mainly fund schools, you see.

**Comment by mattandrews** [comment]
Cool – @stevekeene can you help source one, or should we wait till Chloë is back?

**Comment by stevekeene** [comment]
Hi @mattandrews . This folder has images we can use: https://drive.google.com/drive/folders/0B7fxLPBEvBVLWWN0dFdBcVZQYUk?usp=sharing

I'm happy picking one, but not sure which one will work best with the text and search box on the page!

**Comment by mattandrews** [comment]
Cool – let's wait for Chloë to choose the best one then?

**Comment by stevekeene** [comment]
Maybe! Although if we need a new image sooner for any internal reasons the "Young Foundation-Amplify NI" image might work...

**Comment by TomSteinberg** [comment]
Replaced by ticket #12
