### ISSUE TITLE
Minus button doesn't reduce number of items in 'basket' on merch form (page 3)

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#61]
Bug replicates on desktop chrome, and mobile chrome

**Comment by mattandrews** [comment]
This should now be fixed on [production](https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials):
![counter](https://cloud.githubusercontent.com/assets/394376/26405510/71435116-408d-11e7-916b-9cf24fa183b7.gif)
