### ISSUE TITLE
Reduce the number of fields on the merchandise form

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#62]
It seems highly likely that at least some of the questions we're asking on the merch form are not strictly necessary. Investigate whether the Fund and/or supplier definitely needs all of these, and eliminate any that simply make the process more tiresome for users.

**Comment by mattandrews** [comment]
Update after conversation on 10th November:

Fields should now be:

- Name
- Email address
- Address
- Postcode
- Project name
- Grant amount (dropdown)
  - Under £10k
  - Over £10k
  - Don't know
- How are you using the materials? (dropdown)
  - Event
  - Project launch
  - Photo opportunity
  -  Other, please specify (free text field)

**Comment by mattandrews** [comment]
Note this will need translating too.

**Comment by mattandrews** [comment]
Now live [here](https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials).
