### ISSUE TITLE
Make various small design improvements to the contact us page (4)

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#68]
- [x] Add links so that people using mobile devices can tap on phone numbers to call them 
- [x] Ensure that all email addresses are bolded in the same style
- [x] Prevent email addresses trailing off the screen at very small browser sizes (e.g iPhone 4s)
- [ ] The relationship between the hero image and the first question background image looks good on desktop, but seems too crowded on mobile. Find a more attractive way of relating the images to each other. 
- [ ] Adjust margin to the right of 4th section's heading so that text does not overlap image

**Comment by mattandrews** [comment]
That last item is worth your time @ChloeAlper – I did a kind of rush job to make the text readable 

## Before:
![image](https://cloud.githubusercontent.com/assets/394376/26680922/1e49c516-46d3-11e7-9ea2-53254876fd7f.png)

## After:
![image](https://cloud.githubusercontent.com/assets/394376/26680930/25fdf02a-46d3-11e7-8147-0da3ce862d94.png)

**Comment by ChloeAlper** [comment]
Please increase the margin to the right of the header so that the word 'your' sits on the same line as the word 'service'
![screen shot 2017-06-06 at 12 26 02](https://cloud.githubusercontent.com/assets/27225981/26827220/2cc00ee0-4ab4-11e7-8f0c-7d971461794e.png)

**Comment by mattandrews** [comment]
Now live :)

![image](https://user-images.githubusercontent.com/394376/26839106-f3232bc4-4ad9-11e7-9c19-6ae44f4cd58a.png)

**Comment by ChloeAlper** [comment]
Ace!
