### ISSUE TITLE
Replace 'contact press team' page

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#69]
The current page resides at:
https://www.biglotteryfund.org.uk/news-and-events/contact-press-team
https://www.biglotteryfund.org.uk/welsh/news-and-events/contact-press-team

It simply doesn't need to be a separate page as long as we make sure that he new /contact page has a good set of press instructions at the bottom. These changes need to be made:

- [x] Move the press section to be the last sub-section section of the new contacts page
- [x] Add the following text to the press sub-section of the new contacts page: 'Broadcast Interviews. For broadcast interviews with the Big Lottery Fund, the ISDN line for our in-house studio is 020 7211 1688. Please contact the UK press office first on 020 7211 1888 to arrange interviews.'
- [x] Add an anchor tag for the press section, to enable deep linking from other parts of the site and from emails/press releases etc
- [x] Redirect to the two pre-existing press page URLs above to deeplink direct to the new anchor tag location

**Comment by mattandrews** [comment]
This could be done alongside #70 and #77 – again, just needs a photo/colour combo.

**Comment by mattandrews** [comment]
... er, actually, this can just happen – it's going in the existing Press section. Sorry!

**Comment by mattandrews** [comment]
@TomSteinberg – I've added this on the TEST environment. Can you confirm you're happy it works (eg. visit the above URLs and switch domain to TEST)? If so, I'll deploy to LIVE and add these URLs to Cloudfront.

**Comment by mattandrews** [comment]
Now live!
