### ISSUE TITLE
Design and deploy SMT page

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#691]

**Comment by stevekeene** [comment]
Minor copy change required on this, request from Gemma: "Pls could we change my bio to remove refs to EasyPeasy? It’s out of date as I haven’t been involved with the company since I started at the Fund. "

**Comment by davidrapson** [comment]
![smt](https://user-images.githubusercontent.com/123386/36897253-bd43f4f4-1e0d-11e8-807f-38d7b7515811.gif)

**Comment by davidrapson** [comment]
Now ready to go live.

**Comment by davidrapson** [comment]
This is now live https://www.biglotteryfund.org.uk/about/our-people/senior-management-team
