### ISSUE TITLE
Re-crop old style images

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#696]
- [x] https://www.biglotteryfund.org.uk/about/customer-service/data-protection
- [x] https://www.biglotteryfund.org.uk/about/customer-service/freedom-of-information
- [x] https://www.biglotteryfund.org.uk/contact
- [x] https://www.biglotteryfund.org.uk/data
- [x] https://www.biglotteryfund.org.uk/empowering-young-people
- [x] https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding
- [x] https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/grant-acknowledgement-and-logos
- [x] https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/ordering-free-materials
- [x] https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/press
- [x] https://www.biglotteryfund.org.uk/funding/funding-guidance/managing-your-funding/social-media

**Comment by mattandrews** [comment]
See https://github.com/biglotteryfund/blf-alpha/issues/202 and https://github.com/biglotteryfund/blf-alpha/issues/360 for when this is done!

**Comment by davidrapson** [comment]
This is now done!
