### ISSUE TITLE
Implement text changes to remove ambiguity on NLAFA England page

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#697]

**Comment by mattandrews** [comment]
Think this is done now – I just added Greg's new text: https://www.biglotteryfund.org.uk/funding/programmes/national-lottery-awards-for-all-england

**Comment by mattandrews** [comment]
Needs double checking!

**Comment by mattandrews** [comment]
... double checked, turned out I had some old copy. Have now updated it and it's much less ambiguous:

![image](https://user-images.githubusercontent.com/394376/37457297-776713ae-2839-11e8-870d-a64847887634.png)
