### ISSUE TITLE
Add a "How To Complain" (70) section to Contact Us page (4)

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#70]
We are not going to make a new complaints page – we're going to replace the current complaints page with a new section on the Contact page.

**Comment by mattandrews** [comment]
To complete this, we just need a picture/colour combo to go with the new Complaints box, eg. like one of these:

![image](https://user-images.githubusercontent.com/394376/26879171-02da267c-4b88-11e7-83c7-a407b1c650d4.png)

**Comment by ChloeAlper** [comment]
Please see design attached @stevekeene @TomSteinberg @mattandrews 
![4-contact-us](https://user-images.githubusercontent.com/27225981/26884632-21a9c714-4b98-11e7-80f2-61fcb3f7c8b2.png)

**Comment by ChloeAlper** [comment]
The colours were camouflaged by the photos, please see this version instead @stevekeene @TomSteinberg @mattandrews :
![4-contact-us](https://user-images.githubusercontent.com/27225981/26884860-b4d2651e-4b98-11e7-8a2b-b77709ef84b0.png)

**Comment by TomSteinberg** [comment]
Looking good. Three suggestions:
1 - the 'Telephone' 'email' and 'address' heading in the complaints section is nice and you should echo it in the fraud section, for consistency
2 - 'view our complaints procedure' should be a link
3 - The complaints section is actually about complaints and comments, so why not change the section header to say that?

**Comment by stevekeene** [comment]
Re; Tom's point 3 - I think we need to decide on how best to make sure that "How do I get in contact if I have feedback about your service?" and "Making a complaint" don't overlap too much. Perhaps the former is very "comment" focused and the latter more geared towards complaints? 

Also perhaps these new items need to be reworded "How do I make a complaint?" and "How do I report fraud?" to mirror rest of the page?

But looks good!

**Comment by ChloeAlper** [comment]
Please see changes attached. @stevekeene I think the fraud section's copy might need a little tweak so that it follows the same 'Telephone: ... Address: ' format as the section above it (I have clumsily dumped the word 'Address' at the top of the fraud address for the time being)

![4-contact-us](https://user-images.githubusercontent.com/27225981/26886172-a467f366-4b9c-11e7-9110-258240b2e6a9.png)

**Comment by stevekeene** [comment]
Thanks @ChloeAlper - I've tweaked the PDD to show what the text should be for the Fraud item.

**Comment by stevekeene** [comment]
I've also tweaked the PDD for Making a complaint to mirror formatting of address etc of other items.

**Comment by mattandrews** [comment]
Now live!
