### ISSUE TITLE
Design, build, test and launch homepage (28)

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#75]

**Comment by ChloeAlper** [comment]
Please see updated wireframe @stevekeene @TomSteinberg 
![home-wire-20170609](https://user-images.githubusercontent.com/27225981/26978066-f7d72edc-4d21-11e7-9954-3b5ebd12bef7.png)

**Comment by TomSteinberg** [comment]
Two changes please.
i) Please be consistent with £10,000 (i.e use the comma)
ii) The whole final section (news stories plus social media) needs a re-think based on feedback. The challenge now is to incorporate these elements into one section:
- A feed of recent tweets, syndicated in
- Clear invitations to follow on Facebook and Instagram but *not* syndicated content (this is to avoid too much identical content in the feeds)
- A more prominent invitation to sign up for the ebulletin

**Comment by ChloeAlper** [comment]
Updated wireframe:
![home-wire-20170613](https://user-images.githubusercontent.com/27225981/27089295-e438cf60-5051-11e7-9c6d-7f9a797f93ea.png)

**Comment by ChloeAlper** [comment]
Please see home page design @TomSteinberg @stevekeene @mattandrews:
![home](https://user-images.githubusercontent.com/27225981/27089422-322f17ba-5052-11e7-84cf-7a38c1fe3796.png)

**Comment by ChloeAlper** [comment]
Please find updated version attached @TomSteinberg @stevekeene @mattandrews:
![home](https://user-images.githubusercontent.com/27225981/27127836-67569560-50f4-11e7-981c-39af0b632779.png)

**Comment by mattandrews** [comment]
It looks great, really nice work @ChloeAlper! 👍  🏠  📄

**Comment by TomSteinberg** [comment]
@ChloeAlper This is looking really strong. Time to start getting some feedback I think.

**Comment by TomSteinberg** [comment]
Feedback - a call to arms would help, either:

'Here's how you can make a difference in your community.'
'Do you want to make a difference in your community.'

**Comment by stevekeene** [comment]
Looks excellent, thank you!

One tiny, non-important suggestion would be to centre the text on the Apply for Funding buttons, but I don't mind them as they are!

**Comment by ChloeAlper** [comment]
Please see change attached
• addition of 'here's how you can make a difference...' line at top of page:
![home-20170614](https://user-images.githubusercontent.com/27225981/27142930-8082fefe-5124-11e7-952c-fced32c1704a.png)

**Comment by ChloeAlper** [comment]
Ellipses removed from 'Here's how...' introductory sentence:
![home20170615](https://user-images.githubusercontent.com/27225981/27172641-ddac0fd8-51ad-11e7-87ff-92cc1ce004d0.png)

**Comment by mattandrews** [comment]
Might be worth pointing out on the ebulletin thing – @stevekeene and I spoke to the suppliers for that yesterday, and there are two mandatory fields: email address and the country (England, Scotland, Wales or NI) whose newsletter you want. Currently you can select multiple newsletters to sign up to, not sure how many people do this. We could either incorporate that field (dropdown maybe, rather than 4 tickboxes like now?) into this page, to make it a one-click signup, or make it so when you enter your email address here, you get taken to another page which asks you for the other details (optionally your name, too)?

**Comment by TomSteinberg** [comment]
@mattandrews It does feel to me like we should be able to fit all the preferences into this one space. I wonder if we could simple offer each country and 'all' as a pulldown menu? That way the number of page elements is kept to a minimum.

**Comment by TomSteinberg** [comment]
@ChloeAlper One small thing - I think you might be using an old copy of the footer because it has the old logo in it

**Comment by ChloeAlper** [comment]
I have mocked up some versions of the home page with less than four news stories. I have also: 
• Reduced the height of the hero 
• Made the 'Here's how you can make a difference...' text look less clickable

![home-4-news-items](https://user-images.githubusercontent.com/27225981/27535429-b7caacb2-5a62-11e7-8555-8a4f7268f6ff.png)

![home-3-news-items](https://user-images.githubusercontent.com/27225981/27535475-e46f0894-5a62-11e7-9594-8273182e7b02.png)

![home-2-news-items](https://user-images.githubusercontent.com/27225981/27535558-483dc0cc-5a63-11e7-9a79-585202f896d9.png)

![home-1-news-item](https://user-images.githubusercontent.com/27225981/27535565-4f25aba2-5a63-11e7-810c-db624941e362.png)

**Comment by ChloeAlper** [comment]
Here is a hero-less home page. Please have a look @TomSteinberg @stevekeene 

![home-20170627](https://user-images.githubusercontent.com/27225981/27595094-9b06e54a-5b53-11e7-9bad-7edbe852affc.png)

**Comment by ChloeAlper** [comment]
Please see new e-bulletin sign up box at the bottom of the page @TomSteinberg @mattandrews @stevekeene 
![home-20170629](https://user-images.githubusercontent.com/27225981/27691191-372e664a-5cdb-11e7-8ade-eb289208e0af.png)

**Comment by mattandrews** [comment]
Ooh that's nice. Stands out much more now. I like it 👍

**Comment by ChloeAlper** [comment]
Subscribe button altered slightly:
![home-20170629-2](https://user-images.githubusercontent.com/27225981/27691636-84e5f3a2-5cdc-11e7-9250-0d096b2ad9ed.png)

**Comment by stevekeene** [comment]
Looks good - very clear!

One other small thing - the under 10k and over 10k buttons - should the text be centred?

**Comment by ChloeAlper** [comment]
Thanks for your feedback @stevekeene. I had left-aligned those buttons along with the text in the boxes above them, but I have centred them now:

![home-20170629-3](https://user-images.githubusercontent.com/27225981/27692775-7a0e4594-5cdf-11e7-8fc6-1c301bf075ac.png)

**Comment by stevekeene** [comment]
Great stuff, thanks!

**Comment by TomSteinberg** [comment]
Looks ready for a first build

**Comment by ChloeAlper** [comment]
Updated e-bulletin section attached:
![home-20170630](https://user-images.githubusercontent.com/27225981/27732888-4ca0701c-5d8b-11e7-8d4a-6666c2a0f709.png)

**Comment by ChloeAlper** [comment]
Here's the handover doc @mattandrews 

![home-handover-20170630](https://user-images.githubusercontent.com/27225981/27738086-52c22cb2-5da2-11e7-9eb0-dbf28e12468c.png)

**Comment by ChloeAlper** [comment]
Hi @mattandrews , please see tweaks doc attached
![small-changes](https://user-images.githubusercontent.com/27225981/27907646-74ed84e2-6240-11e7-91a4-a9395c6d0cb2.png)

**Comment by ChloeAlper** [comment]
@mattandrews @stevekeene please see the mobile version of the home page below:
![home-mobile-20170712](https://user-images.githubusercontent.com/27225981/28123352-b3864248-6718-11e7-9898-6f9f15c6bd33.png)

**Comment by stevekeene** [comment]
Update from ebulletin staff:

The thank you should contain key pieces of info about unsubscribe and privacy. 

Can this copy be used:

Thank you for subscribing to receive updates and news from the Big Lottery Fund.  Your personal data is important to us and we will not share it with third parties.  We are sure you will enjoy hearing from us, but you can unsubscribe at any time if you wish.

Wired can provide hyperlink to unsubscribe.

**Comment by stevekeene** [comment]
Design looks good @ChloeAlper - thank you!

I had a little play with the Chrome developer tool to see how it looks on various mobile devices. On all of them the "Apply for funding under £10k" button gets a little cropped on the fold. I wondered if there was a way of moving it up ever so slightly so that it appears fully on the screen without any scrolling necessary when the page loads.

Just something to consider - but happy for this to be left alone if this is actually a means of encouraging people to scroll down to read the rest of the page.

**Comment by ChloeAlper** [comment]
Thanks for your feedback @stevekeene I have shifted things up and reduced the height of the hero:
![home-mobile-20170712-2](https://user-images.githubusercontent.com/27225981/28125198-cf0baca6-671d-11e7-95e2-bfdca4f15abb.png)

**Comment by stevekeene** [comment]
That's brilliant, thank you!

**Comment by mattandrews** [comment]
@ChloeAlper forgot to say, this looks great. 

Would you be able to do a really simple mockup of a success/error message for signing up to the e-bulletin?

**Comment by ChloeAlper** [comment]
@mattandrews , @stevekeene , it's not very exciting but here we go...
![screen shot 2017-07-13 at 11 43 20](https://user-images.githubusercontent.com/27225981/28162862-939ef40e-67c0-11e7-88ce-f503a8d37527.png)

**Comment by stevekeene** [comment]
Looks good, thank you!

Just for reference, the word "unsubscribe" should link out to a page to be provided by the people who look after our ebulletin...

Also at a later date we may want to add a line about frequency of emails sent, as this is best practice, so good to see there will be room for that!

**Comment by ChloeAlper** [comment]
Small change requests to the mobile version below @mattandrews 
![screen shot 2017-07-19 at 12 18 12](https://user-images.githubusercontent.com/27225981/28364488-88ccfdc6-6c7c-11e7-9b5b-c1b9b06e5a08.png)

**Comment by stevekeene** [comment]
Just a couple of things to note re: Matt's build:

We need to make sure all the links work just prior to launch!
We also need to review how the Twitter embed looks and works to ensure it is what we're expecting...

**Comment by ChloeAlper** [comment]
Home page with 'real' copy and hero/vox pop rotations:
![home-20170724](https://user-images.githubusercontent.com/27225981/28513141-cee8da72-704c-11e7-8f7e-d9ffc7fb177e.png)

**Comment by ChloeAlper** [comment]
Updated home page with 'real' copy and hero/vox pop rotations:
![home-20170724-2](https://user-images.githubusercontent.com/27225981/28520891-3e9b8a38-7069-11e7-9880-b57782c0456e.png)

**Comment by mattandrews** [comment]
So as far as I can tell, here's what's left to do on the homepage:

- [ ] Add final copy
- [ ] Get copy translated (including full vox pops / case studies)
- [ ] Add case studies / vox pops to legacy site (eg. for "read more" links)
- [ ] Verify that the A/B test functionality is working (including analytics)
- [ ] Verify the e-bulletin signup works as expected (I've done this but might be worth involving the external company who run this so we can check it's doing what they expect too)
- [ ] Then: Follow regular page signoff steps

Did I miss anything?

**Comment by ChloeAlper** [comment]
@mattandrews please see the handover docs below:

![desktop-home-handover](https://user-images.githubusercontent.com/27225981/30812146-e94b025a-a201-11e7-86df-a1be27600513.png)

![mobile-home-handover](https://user-images.githubusercontent.com/27225981/30812149-ebf0429a-a201-11e7-8018-371afbe425b8.png)

**Comment by ChloeAlper** [comment]
@mattandrews @davidrapson I forgot to include this on the handover doc yesterday:
![desktop-handover](https://user-images.githubusercontent.com/27225981/30865824-8f4356e4-a2cf-11e7-8cb8-4e65f077d3c8.png)
It refers to the fact that an asterisk now suffixes the hero description in the header when the hero image depicted has, for example, received more than one grant. A description of the fact that the grant amount mentioned was awarded within the last 12 months now sits in the footer.

**Comment by mattandrews** [comment]
Thanks. That footnote is only applicable on certain pages, right?

**Comment by ChloeAlper** [comment]
Well really it could be on any page, but it won't be applicable to all hero images

**Comment by davidrapson** [comment]
Started a work-in-progress branch here with my changes, will keep that ticket updated so you can follow along with progress https://github.com/biglotteryfund/blf-alpha/pull/173

**Comment by mattandrews** [comment]
Closing this as we're now live (albeit to a percentage of the audience, but still!).
