### ISSUE TITLE
Design, build and launch page (29) '£10k and below'

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#76]
TBD

**Comment by ChloeAlper** [comment]
I've made some changes to the wireframe following your meetings with Engagement @TomSteinberg @stevekeene:

![10k-and-under-wire-20170612](https://user-images.githubusercontent.com/27225981/27038381-bdb3e214-4f82-11e7-965d-efe6940c7bf3.png)

**Comment by TomSteinberg** [comment]
Looking good - one ordering suggestion though. The sentence that starts 'occasionally the Fund' should be under the country buttons, not above, since this sentence sort of replaces there being an 'All UK' button on this page.

**Comment by stevekeene** [comment]
Yep, looks good. Also might be worth rewording "Find out more here" to something like "Find out more about our UK-wide funding" so that is makes sense on screen readers.

**Comment by stevekeene** [comment]
Also, might be helpful to have a button to link to the over £10K page, for people who have landed directly here but actually need more money.

**Comment by ChloeAlper** [comment]
Updated version attached @TomSteinberg. I made the '+10k info' button suggestion into a text link @stevekeene,  please have a look to see if you think that's ok. 
![10k-and-under-wire-20170612-2](https://user-images.githubusercontent.com/27225981/27041718-a310caa8-4f8c-11e7-8a9a-926fb47e361e.png)

**Comment by ChloeAlper** [comment]
Please see design @TomSteinberg @stevekeene @mattandrews 
Please note that: 
• The project names may well be incorrect because I took them from JPGs, I used them regardless because I wanted to use different title lengths.
• This page's cousin – the above 10k – will use a different highlight colour to continue the colour relationship begun on the home page. 
 
![under-10k](https://user-images.githubusercontent.com/27225981/27232506-2e38c972-52ae-11e7-9e16-5cab206f1d1e.png)

**Comment by mattandrews** [comment]
Ultimately we want people to click on a country destination here, right? Maybe we could emphasise that section even more? Maybe number the heading (as this is step 1)? Or just box it off or give it a strong background colour or something? But really I'm nitpicking, I think this looks awesome. 🔥

**Comment by TomSteinberg** [comment]
I agree with Matt - I think some people would probably think that the main action on this page was currently 'browse all funded projects'. Please could you try some more signposting, either visual or linguistic, to make it more obvious that in order to have any chance of getting any money, you really have to click one of those four country buttons!  Could be something like 'Get started by...' or 'Step 1' or something more smart and subtle.

**Comment by ChloeAlper** [comment]
Could you have a look at this attachment @mattandrews  @TomSteinberg and see if you think this solves it at all?

![under-10k](https://user-images.githubusercontent.com/27225981/27288492-cacb9e98-54fe-11e7-95fd-a0262b3ea76a.png)

**Comment by TomSteinberg** [comment]
I like the way you've used the background colour as subtle emphasis - nice.

Could you please change 'To apply start by...' to 'Want to know more? Start by...' - we don't want people to think that a click on one of those buttons is an irrevocable commitment of some sort. 

Also I just noticed the words 'Some Projects we have funded', which seems a bit clunky. How about 'Examples of projects that have been funded'?

**Comment by ChloeAlper** [comment]
Thanks for your feedback @TomSteinberg , I've changed the titles:
![under-10k](https://user-images.githubusercontent.com/27225981/27289361-8dfadd0a-5501-11e7-8244-8f462599fbcb.png)

**Comment by TomSteinberg** [comment]
👍

**Comment by ChloeAlper** [comment]
Footer updated:
![under-10k](https://user-images.githubusercontent.com/27225981/27298126-5ffb15e6-551f-11e7-923e-3c5bb3e9eb61.png)

**Comment by ChloeAlper** [comment]
[This Page is Going to Make the Page Really Long alert] Sorry for the unavoidably long PNG - I want to check you are happy with the whole page @stevekeene @mattandrews :

![below-10k-mobile](https://user-images.githubusercontent.com/27225981/28178526-b8e2ad9c-67f6-11e7-843d-943872d0d4f6.png)

**Comment by stevekeene** [comment]
Looks good to me!

**Comment by ChloeAlper** [comment]
Hi @mattandrews please see small changes below:
![below-10k_20170619](https://user-images.githubusercontent.com/27225981/28362024-c6736796-6c72-11e7-942d-5e10cd23ee6f.png)

**Comment by mattandrews** [comment]
Thanks! With the bullet point change, is that true for the Jobs page too, eg. this:

<img width="193" alt="screenshot 2017-07-19 11 22 09" src="https://user-images.githubusercontent.com/394376/28362520-94bab3e2-6c74-11e7-91e7-7f0fdf57e37a.png">

**Comment by ChloeAlper** [comment]
If that's ok? It's a minor point that, if it's going to cause headache, you should just ignore

**Comment by mattandrews** [comment]
No not at all, it's much more of a headache to change things in one place and not in another! Just wanted to check.

**Comment by ChloeAlper** [comment]
Correct study images inserted, layout changed and text now relevant:
![screen shot 2017-07-20 at 16 33 42](https://user-images.githubusercontent.com/27225981/28425984-beb0332a-6d69-11e7-8507-baf54f008fd6.png)

**Comment by stevekeene** [comment]
We should remove third sentence of text beneath country buttons "If you would like information about grants over £10k click here"

with

"We also make [grants of more than £10,000](url) for longer term projects" 


Plus...

Papyrus and Welsh Refugee Council blurbs need full-stops at the end of them.

**Comment by ChloeAlper** [comment]
Copy changes made:
![under-10k-20170724](https://user-images.githubusercontent.com/27225981/28526017-12d78d92-707e-11e7-9f23-0059baf15da3.png)

**Comment by mattandrews** [comment]
Here's what's left for this page:

- [ ] Get all finalised text translated (including case studies)
- [ ] Launch legacy site pages for case studies
- [ ] Make sure user journeys are correct (eg. country selection)
- [ ] Then: follow standard signoff checklist

**Comment by ChloeAlper** [comment]
Please check you are happy with this updated page design @TomSteinberg @stevekeene 

![under-10k-20170929](https://user-images.githubusercontent.com/27225981/31006080-32c2368a-a4f3-11e7-82b2-52d2001f90a7.png)

**Comment by stevekeene** [comment]
Very happy with design, but a few things to work out:

Case studies need the text that was in the previous version, and to be three case studies, not six, as they are the main under 10K ones we have
Address info needs to be correct in the footer
The hero image referencing a project getting £7M might seem odd for a page on grants under 10K

**Comment by ChloeAlper** [comment]
Top section of mobile version attached:
![below-10k-mobile](https://user-images.githubusercontent.com/27225981/31012611-4af2b3ee-a50a-11e7-8bd6-b9af0b76dea7.png)

**Comment by mattandrews** [comment]
Now live: https://www.biglotteryfund.org.uk/under10k
