### ISSUE TITLE
Add a "How To Report Fraud" (71) section to Contact Us page (4)

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#77]
We need to add a section to the Contact Us page which contains information about reporting fraud (rather than a fully-fledged page).

**Comment by mattandrews** [comment]
Similarly to #70 we just need an image/colour combo to complete this.

**Comment by mattandrews** [comment]
Now live!

**Comment by ChloeAlper** [comment]
@TomSteinberg please see updated attached:
![contact-us-20170620](https://user-images.githubusercontent.com/27225981/27332459-db3827ae-55b9-11e7-9cb3-fde282f9f170.png)
