### ISSUE TITLE
Small improvements to page (7) jobs page

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#79]
- [ ]  Ensure padding at bottom of text boxes is the same height
- [ ]  Increase padding to left and right of map

**Comment by ChloeAlper** [comment]
Please increase padding to left and right of the map so that, when using a mobile device, user can still scroll the page ![screen shot 2017-06-07 at 14 14 03](https://user-images.githubusercontent.com/27225981/26880356-1b4fab38-4b8c-11e7-93ae-d4f3331e557f.png)

**Comment by ChloeAlper** [comment]
Please make sure padding aa the bottom of all text boxes is the same 
![screen shot 2017-06-07 at 14 21 04](https://user-images.githubusercontent.com/27225981/26880574-ba656834-4b8c-11e7-98c4-c8980ecead42.png)

**Comment by mattandrews** [comment]
Have a look now – have updated it:

![image](https://user-images.githubusercontent.com/394376/26881799-6b3d13e8-4b90-11e7-9126-c6f017d30a9a.png)

![image](https://user-images.githubusercontent.com/394376/26881807-75ef97d4-4b90-11e7-8528-b88786e27633.png)

**Comment by ChloeAlper** [comment]
Ooh great @mattandrews ! I think it might be a touch too wide now! Is it possible to shave 5px off or will you hate me forever?

**Comment by mattandrews** [comment]
@ChloeAlper can we close this now the style guide work is done?

**Comment by ChloeAlper** [comment]
@mattandrews I would say so! I need to add the colours page but maybe that should be a separate ticket
