### ISSUE TITLE
Design, build test and launch 'regions' data pages

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#80]
The first version of the /about/data page will not have a search box on it. This ticket is about delivering pages so that a postcode search box can be added at a later date.

Users entering a postcode from /about/data should be taken to a page that represents the relevant region within the UK. The region pages should contain:

- Total spending for that region in the last year
- A static map showing dots that represent every funded project
- A breakdown of regional spending by type, probably expressed as a table.

**Comment by TomSteinberg** [comment]
OK - so regional lookup from a list of regions is acceptable from an MVP perspective: it works, most users will be fine with that. However, I'm sure user testing should show some people not being comfortable with which region is theirs, and so in time we do need to implement a postcode search. This is functionality we'll ultimately have to deliver in dozens of places, probably, so it doesn't hurt to start solving microservice/API choice & licensing questions sooner rather than later.

**Comment by mattandrews** [comment]
@TomSteinberg is this ticket still applicable, post-Data page?
