### ISSUE TITLE
CSS regression

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#810]
Not sure when it was introduced but it looks like several things are broken:

On mobile/tablet layout, both `u-wide-only` and `u-not-wide` elements are visible (should be one or the other):

![image](https://user-images.githubusercontent.com/394376/37893764-e9935350-30d3-11e8-9c12-39e123c69428.png)

And on mobile, toggling the off-canvas menu has no effect (it adds the `show-off-canvas` class to the `<html>` element, but its CSS isn't applying to the rest of the page.

We should urgently fix this, but also add some tests to ensure this can't happen again (particularly the off-canvas button, as this effectively makes the site non-navigable from mobile).

**Comment by mattandrews** [comment]
Okay so this is "fixed" in the sense that it's no longer effecting production, but the underlying issue remains that it's possible for us to break mobile nav with a CSS bug.

I want to add a test for this but we no longer have PhantomJS in the app so I'm not clear what the best way to test this is. We can write a `mocha` test to verify that clicking the hamburger icons adds the relevant classes, but that wouldn't have caught this error. Thoughts @davidrapson?

**Comment by davidrapson** [comment]
Handled by new Cypress tests.
