### ISSUE TITLE
Amendments to Contact us page (4) 

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#83]
It seems sensible to move "How do I get in contact about anything else?" to the last item on the page.

Smallish copy changes, so maintain consistency for address, phone etc. This copy is also now in PDDs 70 and 71.

Change "How do I make a complaint?" copy to:

**At the Big Lottery Fund we try to give the best service possible. However we recognise that this does not always happen and you may wish to make a complaint.

Making a complaint will not affect your chances of receiving a grant from us in the future. 

View our complaints procedure [link to 8 page complaints doc: https://www.biglotteryfund.org.uk/-/media/Files/Corporate%20documents/Customer%20service%20documents/complaints_procedure.pdf]

We are interested in any comments that you may wish to make, so don’t worry whether your concerns fit with the description of a complaint.

We also welcome comments from members of the public who have concerns over an application that we have received or a project that we have funded. 

You can share your concerns or complaints with us verbally or in writing and our contact details are:

Phone: 0191 376 1704

Email: customer.services@biglotteryfund.org.uk  

Address: Customer Services, Big Lottery Fund, 2 St James' Gate, Newcastle, NE1 4BE**

Change "How do I report fraud?" copy to:

**The Big Lottery Fund is committed to preventing and detecting fraud.

If you suspect that someone is stealing from or defrauding the Big Lottery Fund help us do something about it by getting in touch with us.
 
Phone: 0800 496 9991
 
Email: fraud@biglotteryfund.org.uk  

Address: Head of Internal Audit, 3 Embassy Drive, Edgbaston, Birmingham, 
B15 1TR**

And not an absolute dealbreaker, but email addresses are sometimes carrying over to the next line, which looks odd:
![image](https://user-images.githubusercontent.com/394376/26936288-265d7bce-4c66-11e7-8d51-99cb550dd932.png)

**Comment by mattandrews** [comment]
These changes are done and live.
