### ISSUE TITLE
Design, build, test and launch page (84) 'Data Protection'

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#84]

**Comment by ChloeAlper** [comment]
Please see design @stevekeene @TomSteinberg @mattandrews 
![84-data-protection](https://user-images.githubusercontent.com/27225981/27182171-39e6dade-51d2-11e7-9e28-d0c6b7d7f9a1.png)

**Comment by mattandrews** [comment]
This is done from my end but I need the hero images – can you either save them out or share the PSD?

**Comment by ChloeAlper** [comment]
Sure - the PSD is now in our Dropbox

**Comment by mattandrews** [comment]
Now live: https://www.biglotteryfund.org.uk/about-big/customer-service/data-protection
