### ISSUE TITLE
Accessibility tasks

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#842]
## STAS-F02

- [x] Confirm skip-nav works on https://www.biglotteryfund.org.uk/about/ebulletin (@davidrapson)

## STAS-F03

- [x] Review heading structure on a range of pages and make fixes as needed (@davidrapson)
- [x] Add sectioning element to footer links to create a new heading flow for this section (@davidrapson)

## STAS-F09

- [x] Review current alt-text, focus on images coming from the CMS (@mattandrews)

## STAS-F10

- [x] Double check empty heading has been fixed on the homepage (@davidrapson)

## STAS-F11

- [x] Add fieldset/legend to ebulletin (@mattandrews)
- [x] Add fieldset/legend to micro-survey. Move HTML to end of the page (@mattandrews)

## STAS-F14

- [x] ~Confirm if any action is needed for home/logo link in header (@davidrapson)~ Decided that this is an acceptable trade-off.

## STAS-F17

- [x] Review how tables work in the CMS (@mattandrews)
- [x] Review responsive styles for data-tables from CMS content (@mattandrews)

### STAS-F18

- [x] Review fallback content for static-iframes, e.g. google maps (@davidrapson)

### STAS-A01

- [x] Review link text content to make sure it's understandable, notably on homepage (@davidrapson)

### STAS-A02

- [x] Update static documents to reference file size / type within link text (@mattandrews)
- [x] Investigate methods of automating this in the CMS? (@mattandrews)

### STAS-A03

- [x] Make accessibility statement part of the skip-links (@davidrapson)
- [x] Migrate accessibility statement page to the CMS (@davidrapson)

## Extracted out into separate tickets

- STAS-F19 Review approaches for contrast ratios. (@LynseyJReynolds)
- STAS-A03 Start process of rewriting accessibility statement (@LynseyJReynolds)

**Comment by mattandrews** [comment]
Re: methods of automating document link info (filetype/size) – nah, not possible out of the box unless we wanted to edit Craft's core functionality to change how it outputs file links. Probably more trouble than it's worth to just manually supply these.

**Comment by mattandrews** [comment]
And on responsive tables: feels like a case-by-case thing when we come across one that needs it. Right now the only one we have is only 3 columns and works on mobile as-is.

**Comment by davidrapson** [comment]
"And on responsive tables: feels like a case-by-case thing when we come across one that needs it. Right now the only one we have is only 3 columns and works on mobile as-is." 

+1 to this
