### ISSUE TITLE
Design, build, test and launch page (85) 'Freedom of Information'

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#85]

**Comment by ChloeAlper** [comment]
Please see design @stevekeene @TomSteinberg @mattandrews 
![85-freedom-of-information](https://user-images.githubusercontent.com/27225981/27140809-66922250-511e-11e7-8bd1-ccfa50692b52.png)

**Comment by stevekeene** [comment]
Looks great, thanks Chloe!

**Comment by mattandrews** [comment]
This is now live: https://www.biglotteryfund.org.uk/about-big/customer-service/freedom-of-information
