### ISSUE TITLE
Additional copy for page (4) 'Jobs'

### ISSUE THREAD

**Issue by stevekeene** [biglotteryfund/blf-alpha#86]
In final 'Equalities' section - 

New paragraph to begin section:

"The Big Lottery Fund is committed to considering and addressing equality issues in all aspects of its business, including how we recruit and employ our staff. This means we think about the needs and experiences of people from different backgrounds (for example, by gender, race, disability and sexual orientation) and we work to ensure that as far as possible we avoid treating people unfairly."

New paragraph to follow "The Big Lottery Fund will make any reasonable adjustments" paragraph:

"If you have a disability that prevents you from completing an online form, please contact the HR Helpdesk, on 0121 345 8884 or email HRhelpdesk@biglotteryfund.org, who will be happy to help."

**Comment by mattandrews** [comment]
Cheers – will get this translated and added!

**Comment by mattandrews** [comment]
Now live: https://www.biglotteryfund.org.uk/jobs and https://www.biglotteryfund.org.uk/welsh/jobs
