### ISSUE TITLE
Reduce hero images on all pages by 30px

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#87]
Comes from internal feedback

**Comment by mattandrews** [comment]
I was just looking at this – there's a way we can do this right now without having to resize all the images manually, but it'll mean centering them in the available space (eg. cropping a bit off the top/bottom):

## Current design vs proposed (30px shorter)

![image](https://user-images.githubusercontent.com/394376/27283161-eff4e2ec-54ea-11e7-8165-520ec0aecca0.png)

You can see here that the image on the right is 30px shorter, and it's been scaled to fill the space (meaning it loses `15px` above/below). Would that be acceptable or should we just re-crop them (and that way control the cropping)?

**Comment by ChloeAlper** [comment]
I would rather we had more control over the crop to be honest. I think that means we need to do it manually...

**Comment by mattandrews** [comment]
That's fine! Let's get a massive cafetiere and some biscuits and churn 'em out in a week or so's time...

**Comment by ChloeAlper** [comment]
Sounds like a plan!
