### ISSUE TITLE
Small changes to page (85) Freedom of Information

### ISSUE THREAD

**Issue by ChloeAlper** [biglotteryfund/blf-alpha#88]
- [x]  Change email address colour to #00bd71
- [x]  Reduce padding above text at top of bounding boxes to 30px

**Comment by ChloeAlper** [comment]
![screen shot 2017-06-15 at 13 01 29](https://user-images.githubusercontent.com/27225981/27180313-cd1e0c44-51ca-11e7-8d0b-1c3530285035.png)

**Comment by mattandrews** [comment]
I think we changed this to 35px earlier, are we changing this to 30px everywhere now?

**Comment by ChloeAlper** [comment]
I think it might have changed itself back from 35px because on http://blf-test-lb-1246468266.eu-west-1.elb.amazonaws.com/about-big/customer-service/freedom-of-information it is currently 43px

**Comment by mattandrews** [comment]
(edited the test site link out of the above comment!)

**Comment by mattandrews** [comment]
Have updated this now on TEST, give it a look!

**Comment by ChloeAlper** [comment]
It looks fab, thank you!
