### ISSUE TITLE
Install CloudWatch logs agent on instances

### ISSUE THREAD

**Issue by davidrapson** [biglotteryfund/blf-alpha#890]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Install-CloudWatch-Agent.html

**Comment by mattandrews** [comment]
Ensure GDPR compliance!

**Comment by davidrapson** [comment]
Closing this as we've been running this since https://github.com/biglotteryfund/blf-alpha/pull/2001
