### ISSUE TITLE
Build temporary grants database homepage

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#892]
Users still need to be given access to the legacy grants database that exists on our site. But we need to build a new homepage for it that:

a) Explains we're trying to do better, and that solicits user-feedback on this function
b) Replicates the current fields and 'search' button
c) Provides an outbound link to GrantNav, as another option.

When users submit search queries in the fields, they should be directed to search results that are powered by the legacy Sitecore hosted search.

**Comment by mattandrews** [comment]
I wonder if we could do something to improve the current search which would augment it by updating the URL with parameters.

**Comment by davidrapson** [comment]
This was launched at the end of last week and is live at https://www.biglotteryfund.org.uk/funding/past-grants
