### ISSUE TITLE
Migrate non-CMS pages to Craft

### ISSUE THREAD

**Issue by mattandrews** [biglotteryfund/blf-alpha#947]
# Content pages still in the codebase

## Under £10k / Over £10k – medium
- has some "hard-coded" UI
- examples of projects could/should change

## Homepage – low priority
- brand text
- case studies / images
- social media links

## Regional homepages (NI / Wales) – low
- funding spiel
- programme examples (!)
- funding stats
- ideas supported

## About page – low
- complex layout / shouldn't be changed often

## Research – low
- just links to top-level sections/pages

# Non-content pages / other (eg. no need for CMS)
- general UI
- ebulletin
- /funding (mainly just links, though has hard-coded programmes)

# Done

## Data – n/a (done!)
- headline stats
- regional award stats (lives in a JSON file)

## Jobs – high
- links out to external jobs page

## Benefits – high
- content changes fairly often

## Social Media Publicity / Press Coverage – high
- should just be in CMS

## Managing Your Funding – medium
- could link out to sub-pages automatically (code exists for this)

## Contact – high
- methods
- offices
- topics (eg. complaints, queries, press etc)

## Free Branded Material – medium
- Complex UI (could be better in CMS though?)

## Logos – low
- ~Intro text could be customisable~
- How To Use Logo would work well in CMS

**Comment by davidrapson** [comment]
Hey, we did this 😃
