### ISSUE TITLE
Examine whether it's possible to take Google searches for 'complaints' and send them straight to the anchor link under complaints

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#97]

**Comment by mattandrews** [comment]
It sounds like we want [Sitelinks](https://support.google.com/webmasters/answer/47334?hl=en) for this:

![image](https://user-images.githubusercontent.com/394376/27688870-0a7ac924-5cd4-11e7-8428-84d371526838.png)

Sadly:

>At the moment, sitelinks are automated. We're always working to improve our sitelinks algorithms, and we may incorporate webmaster input in the future. There are best practices you can follow, however, to improve the quality of your sitelinks. For example, for your site's internal links, make sure you use anchor text and alt text that's informative, compact, and avoids repetition.

... I'm not sure right now what other options we have to improve this besides adding lots of links to the site marked "complaints" which point directly to https://www.biglotteryfund.org.uk/contact#complaints – I'm also not sure if Google ever indexes anchors like this in results – [this article](https://www.searchenginepeople.com/blog/anchor-links.html) suggests not.

One thing we could do is make the anchor tag sit on some text – right now it's on a box of content. I can try moving it to the text "How do I make a complaint" which might work, but it's up to Google by the sounds of it.
