### ISSUE TITLE
Research & design a good way of exposing data released under our transparency agenda

### ISSUE THREAD

**Issue by TomSteinberg** [biglotteryfund/blf-alpha#99]
Questions that need discussing:
1 - Does this belong entirely on the FOI page?
2 - What are the main priorities?
3 - Which datasets need refreshing how often?
4 - What process can be put in place so that they get refreshed in good order?
5 - What are our legal obligations or best-practice expectations from central govt?

**Comment by mattandrews** [comment]
Relates to #92
